name: my_application
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-78.0.dev

publish_to: none

# Add regular dependencies here.
dependencies:
  my_shopping_cart:
    path: ../my_shopping_cart
  messages:
    path: ../../../messages
  messages_builder:
    path: ../../../messages_builder
  logging: ^1.2.0
  native_assets_cli: ^0.6.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
