// Copyright (c) 2024, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN
//
//    dart tool/regenerate_hashes.dart
//

import 'package:code_assets/code_assets.dart' show Architecture, OS;

const fileHashes = <(OS, Architecture, String), String>{
  (OS.linux, Architecture.arm, 'dynamic'):
      '02fa85557cdbf8a6dc9144b612ff3860db278c27ddeffd1add9783c32c4d6e5e',
  (OS.linux, Architecture.arm, 'static'):
      'f399c2b023b065d120261ed2c74fd272f64448cf5e969523769e9bff10cb2c4b',
  (OS.linux, Architecture.arm, 'static_data'):
      '895db975e0267c940490efa8161b2e8f7e5b28cb992a07b51ea1e3380c206626',
  (OS.linux, Architecture.arm64, 'dynamic'):
      'c3d5790fce3a87f523a26451fc0207fd364fd3101a1d473da0670c95dbc8370b',
  (OS.linux, Architecture.arm64, 'static'):
      'f0967eb7f30afa50eb26e82d392e2eb6a51786c9ace95509497fdcd7c01494e1',
  (OS.linux, Architecture.arm64, 'static_data'):
      'e3cf0a5ac2218e0c4e9a71877e9bccfcf6a746bcd0dbe537d34e6df9e8248fa6',
  (OS.linux, Architecture.riscv64, 'dynamic'):
      'd003808cf7d8ce26d1bd9cbe61cc1a1de32575fe843a5ad5ebcdf6de792b3202',
  (OS.linux, Architecture.riscv64, 'static'):
      'f1b192dde2ddbfb2438b47d9824de320bd22f1b89cc83c837320538f68d05071',
  (OS.linux, Architecture.riscv64, 'static_data'):
      '2b950eb7c68ca1eb609235a6893983ac6ca74743027ebdaecb749a329ac3d84a',
  (OS.linux, Architecture.x64, 'dynamic'):
      'f49468498f9e2ea2c80d1dccca40cefa3e077ba98c7eea5cb97bc8fa30fc3f70',
  (OS.linux, Architecture.x64, 'static'):
      '3f66ec621505266e8550f30c1b34f9b191dede865d2cc2b30bdfe726a9fdf71b',
  (OS.linux, Architecture.x64, 'static_data'):
      'ee831a88ccc995d2c057a31f82a050def2f8984bde24a173a5e51e2785765ee7',
  (OS.windows, Architecture.arm64, 'dynamic'):
      '230ff791b7bc8e9eda33fbcd1b1e1f21790a4a58c3f71d69b635353de5afae75',
  (OS.windows, Architecture.arm64, 'static'):
      'ea61dfae52865f9cffecc8bb9e7b6e5aa99eb8085d1d2e47d6772433931aeb3c',
  (OS.windows, Architecture.arm64, 'static_data'):
      '2195de4bdcbf065839847c59a4c94df50bc67511b00fa54a2f032853290c82d2',
  (OS.windows, Architecture.ia32, 'dynamic'):
      '22cacafa7e5328eb030910b7f22dfbde8e2d68e1b8cf9223f5c1f1e1d5f801d0',
  (OS.windows, Architecture.ia32, 'static'):
      '1e2eb4191dd255d4d6f819052b07a6db16000e96e8e5f52d174af7f7afb405a0',
  (OS.windows, Architecture.ia32, 'static_data'):
      '7aa63e52b00b5952a2a7433274ebec70119bb19e632ead98fb99a65dbb597e6f',
  (OS.windows, Architecture.x64, 'dynamic'):
      '95a99f278578184015aaeff1cb8edfd5b0da02dcd83b4768c0cdeb4ba3f97e89',
  (OS.windows, Architecture.x64, 'static'):
      'a58044e0f722188994f6a4221fd31c9dd7c80f1d6639ed616a045b6c7bf4211d',
  (OS.windows, Architecture.x64, 'static_data'):
      '2091ce374817306729096fc2447a20b8da36fc1f7527d8c2e37d84ea32bd8f03',
  (OS.android, Architecture.arm, 'dynamic'):
      '558fb05cbd064f2da74270d2668fb138bbd5e24df3a84db3db02a48a37b9a2f3',
  (OS.android, Architecture.arm, 'static'):
      '78c0f9b798918b6bef814f42a479a37ccd7f25c92843d6db58a8b1a33cbc6030',
  (OS.android, Architecture.arm, 'static_data'):
      '22cf32c5416b20f68bb9d82e6613ba9db5e8a9a7a7c32070903ff0b94ce4fa1a',
  (OS.android, Architecture.arm64, 'dynamic'):
      '21540da76bd332bc12a9243972204d4953bb987dbd5f768788d5937f2fbfd82a',
  (OS.android, Architecture.arm64, 'static'):
      '8dfeef96c9e1f42b3b9698327d2813ccf070b332e5550dd566c39fbf2000b894',
  (OS.android, Architecture.arm64, 'static_data'):
      '0da802c359a7f541f747e863dd671076af7747b6b430d5500eedfe300ed7153b',
  (OS.android, Architecture.ia32, 'dynamic'):
      'c89d646e0bd6b8170ed9f09ee7d2f08456cb63739ef5096d2adbd4b8ff077b30',
  (OS.android, Architecture.ia32, 'static'):
      '9dedb281cc0cbb3c28f8ea23335bbbce80332274e9328464f920aa3522b2906c',
  (OS.android, Architecture.ia32, 'static_data'):
      '0dfd143a9e42d7291ea7d375e96e62e979f6f64ee0ce465bdfa61c114e26c98a',
  (OS.android, Architecture.x64, 'dynamic'):
      'd781cb7e376ddce56bccddb869ea1159b58e879507456e570e4ae559dfa823a7',
  (OS.android, Architecture.x64, 'static'):
      '85fb0475c06d098c1825a25092fbfae16cd1bb4a9b7536e2dffdd0b09c6a6132',
  (OS.android, Architecture.x64, 'static_data'):
      'de2833d49461399397eaef9a7197b8add17e073af0b40708e9dc6bb11aa05f19',
  (OS.macOS, Architecture.arm64, 'dynamic'):
      '00cd1afeb3162ec81459e64b92eb63a6e774b93b2ff2f11584830eb61f02f35b',
  (OS.macOS, Architecture.arm64, 'static'):
      '024f4ebc095f4cd77a4091f99ba43bab490a05c152da93fddfd22af2c172ed05',
  (OS.macOS, Architecture.arm64, 'static_data'):
      'f33bcd57216d030e26ef8eb9a3e7024cc8a39b46ca71ac65108fb2d6c951590e',
  (OS.macOS, Architecture.x64, 'dynamic'):
      '19668c9fdf88f801767c6c4bff1695ce5c7da11cc140d7f4d8c850c54d505008',
  (OS.macOS, Architecture.x64, 'static'):
      '2027f82e834e88ae81bf2c4321ea013dd55cf803488dd54b0fe7a6847f5d763b',
  (OS.macOS, Architecture.x64, 'static_data'):
      '05a61f31ee40bdba8ec5359a1823aea9fa64402c921850f8dae373b081e68c16',
  (OS.iOS, Architecture.arm64, 'dynamic'):
      '27ffbba024b00b1681fa7d6849b841370df91433b59313b61834e7f7359a7bc6',
  (OS.iOS, Architecture.arm64, 'static'):
      '38014474a256fb5849701717324dcef5532efb6a92632f26a040725fdd059372',
  (OS.iOS, Architecture.arm64, 'static_data'):
      'b5adedf18926ea176f49a4b9c9882608f0c0c0c05bc4bc227a8f2b356d7e5e22',
  (OS.iOS, Architecture.x64, 'dynamic'):
      '3697bd7466e6e608cb20950cb9c5e35c0ead9a793cc100bb395f9faaf0d0de30',
  (OS.iOS, Architecture.x64, 'static'):
      'a111c309c21802cfc983aae8c50f98a9feee8325e30a36129bb706f00a79f97c',
  (OS.iOS, Architecture.x64, 'static_data'):
      '8e95564ea7e4f7d22c6b8f0c67e10006e4d9114aaf07f0c573bba676751caed3',
};
