// Generated by package:messages_builder

import 'dart:async';

import 'package:asset_bundle/asset_bundle.dart';
import 'package:messages/messages_json.dart';
import 'package:messages/resources_asset.dart';

typedef Locale = String;

class AboutPageMessages {
  final IntlObject intlObject;

  Locale currentLocale = 'en';

  late final MessagesAssetBundle bundle;

  Completer<void> loadedMessageBundle = Completer();

  AboutPageMessages(this.intlObject) {
    loadMessageBundle();
  }

  void loadMessageBundle() {
    CachedAssetBundle()
        .load<MessagesAssetBundle>('about_messages')
        .then((loadedBundle) {
      bundle = loadedBundle;
      loadedMessageBundle.complete();
    });
  }

  Iterable<String> get knownLocales => ['en', 'de'];

  @pragma('dart2js:tryInline')
  Future<String> aboutMessage({required String websitename}) async {
    await loadedMessageBundle.future;
    return await generate(
      bundle,
      [websitename],
      currentLocale,
      intlObject,
      AboutPageMessagesEnum.aboutMessage.index,
    );
  }

  @pragma('resource-identifier')
  @pragma('dart2js:resource-identifier')
  @pragma('dart2js:never-inline')
  static Future<String> generate(MessagesAssetBundle bundle, List args,
      String currentLocale, IntlObject intlObject, int index) async {
    final message =
        await bundle.getMessageByIndex(locale: currentLocale, index: index);
    return message.generateString(args, intl: intlObject);
  }
}

enum AboutPageMessagesEnum {
  helloAndWelcome,
  aboutMessage,
  newMessages,
  newMessages2
}
