name: my_shopping_cart
description: "A new Flutter package project."

publish_to: none

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.0
  messages:
    path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  messages_builder:
    path: ../../../messages_builder

package_options:
  messages_builder:
    arb_input_folder: assets/l10n/
    message_output_folder: assets/
    code_output_folder: lib/src/

dependency_overrides:
  messages:
    path: ../..
  messages_builder:
    path: ../../../messages_builder
  messages_serializer:
    path: ../../../messages_serializer

flutter:
  assets:
    - assets/messages.arb.json
