// Copyright (c) 2023, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:io';

import 'package:collection/collection.dart';
import 'package:yaml/yaml.dart';

/// Options for the message data file and code generation.
class GenerationOptions {
  /// The data file serialization, either json or (TBD) binary.
  final SerializationType serialization;

  /// The data file deserialization, either through browser functionalities or
  /// dart native code.
  final DeserializationType deserialization;

  /// The header to add to all generated files, for example for licensing.
  final String header;

  /// The origin of the algorithm for determining which plural case to use.
  final PluralSelectorType pluralSelector;

  /// The target environment (flutter or dart).
  final TargetEnvironment target;

  /// Where the arb files are located.
  final Directory arbFolder;

  /// Where to write the message data files to.
  final Directory messageFolder;

  final Directory generatedCodeFiles;

  final String packageName;

  static const _headerKey = 'header';
  static const _pluralSelectorKey = 'plural_selector';
  static const _arbInputFolderKey = 'arb_input_folder';
  static const _messageOutputFolderKey = 'message_output_folder';
  static const _generatedCodeFilesKey = 'generated_code_files';
  static const _targetKey = 'target';

  static List<String> get validKeys => [
    _pluralSelectorKey,
    _headerKey,
    _arbInputFolderKey,
    _messageOutputFolderKey,
    _generatedCodeFilesKey,
    _targetKey,
  ];

  GenerationOptions({
    required this.serialization,
    required this.deserialization,
    required this.header,
    required this.pluralSelector,
    required this.target,
    required this.packageName,
    required this.arbFolder,
    required this.messageFolder,
    required this.generatedCodeFiles,
  });

  static Future<GenerationOptions> fromPubspec(String pubspecData) async {
    final pubspec = loadYaml(pubspecData) as YamlMap;
    final packageOptions = pubspec['package_options'] as YamlMap?;
    final messagesOptions = packageOptions?['messages_builder'] as YamlMap?;
    final illegalKey = messagesOptions?.keys.firstWhereOrNull(
      (key) => !validKeys.contains(key),
    );
    if (illegalKey != null) {
      throw ArgumentError(
        'The message options contain the illegal key $illegalKey',
      );
    }
    final generationOptions = GenerationOptions(
      serialization: SerializationType.json,
      deserialization: DeserializationType.web,
      header:
          messagesOptions?[_headerKey] as String? ??
          'Generated by package:messages_builder.',
      pluralSelector: _pluralSelector(messagesOptions),
      target: _target(pubspec, messagesOptions),
      packageName: pubspec['name'] as String,
      arbFolder: Directory(
        messagesOptions?[_arbInputFolderKey] as String? ?? 'assets/l10n/',
      ),
      messageFolder: Directory(
        messagesOptions?[_messageOutputFolderKey] as String? ?? 'assets/',
      ),
      generatedCodeFiles: Directory(
        messagesOptions?[_generatedCodeFilesKey] as String? ?? 'lib/src/',
      ),
    );
    return generationOptions;
  }

  static PluralSelectorType _pluralSelector(YamlMap? messagesOptions) {
    final pluralSelectorString =
        messagesOptions?[_pluralSelectorKey] as String?;
    return pluralSelectorString != null
        ? PluralSelectorType.values
              .where((type) => type.name == pluralSelectorString)
              .first
        : PluralSelectorType.intl;
  }

  static TargetEnvironment _target(YamlMap pubspec, YamlMap? messagesOptions) {
    final targetString = messagesOptions?[_targetKey] as String?;
    if (targetString != null) {
      final matched = TargetEnvironment.values.firstWhereOrNull(
        (type) => type.name == targetString,
      );
      if (matched == null) {
        throw ArgumentError(
          'The message options contain the illegal target value '
          '"$targetString". Valid values are: flutter, dart, manual.',
        );
      }
      return matched;
    }
    return _isFlutterApp(pubspec)
        ? TargetEnvironment.flutter
        : TargetEnvironment.dart;
  }

  static bool _isFlutterApp(YamlMap pubspec) {
    if (pubspec.containsKey('flutter')) return true;
    final dependencies = pubspec['dependencies'];
    if (dependencies is YamlMap && dependencies.containsKey('flutter')) {
      return true;
    }
    final devDependencies = pubspec['dev_dependencies'];
    if (devDependencies is YamlMap && devDependencies.containsKey('flutter')) {
      return true;
    }
    return false;
  }
}

enum SerializationType { json }

enum DeserializationType { web }

/// Target environment for generated message code and assets.
enum TargetEnvironment { flutter, dart, manual }

/// The origin of the algorithm for determining which plural case to use.
enum PluralSelectorType {
  /// From `package:intl`.
  intl,

  /// From `package:intl4x`.
  intl4x,

  /// A user-specified algorithm.
  custom,
}
