// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:intl4x/datetime_format.dart';

// Generated content: Do not edit this file manually.
// Regenerate by running `dart run test/tools/regenerate_conformance_data.dart`

final mOptions = {
  (
    TimePrecision.hour,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.hour,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.hour,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.hour, DateTimeLength.long, DateTimeAlignment.auto, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.hour,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.hour,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.hour,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.hour, DateTimeLength.long, DateTimeAlignment.column, null):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.hour, DateTimeLength.long, null, YearStyle.auto):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.hour, DateTimeLength.long, null, YearStyle.full):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.hour, DateTimeLength.long, null, YearStyle.withEra):
      'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.hour, DateTimeLength.long, null, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.hour,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.hour,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.hour,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.hour, DateTimeLength.medium, DateTimeAlignment.auto, null):
      'Mi., 18.06.2025',
  (
    TimePrecision.hour,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.hour,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.hour,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.hour, DateTimeLength.medium, DateTimeAlignment.column, null):
      'Mi., 18.06.2025',
  (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.auto):
      'Mi., 18.06.2025',
  (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.hour, DateTimeLength.medium, null, null): 'Mi., 18.06.2025',
  (
    TimePrecision.hour,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.hour,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.hour,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.hour, DateTimeLength.short, DateTimeAlignment.auto, null):
      'Mi., 18.06.25',
  (
    TimePrecision.hour,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.hour,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.hour,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.hour, DateTimeLength.short, DateTimeAlignment.column, null):
      'Mi., 18.06.25',
  (TimePrecision.hour, DateTimeLength.short, null, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.hour, DateTimeLength.short, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.hour, DateTimeLength.short, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.hour, DateTimeLength.short, null, null): 'Mi., 18.06.25',
  (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.hour, null, DateTimeAlignment.auto, null): 'Mi., 18.06.25',
  (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.hour, null, DateTimeAlignment.column, null): 'Mi., 18.06.25',
  (TimePrecision.hour, null, null, YearStyle.auto): 'Mi., 18.06.25',
  (TimePrecision.hour, null, null, YearStyle.full): 'Mi., 18.06.2025',
  (TimePrecision.hour, null, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.hour, null, null, null): 'Mi., 18.06.25',
  (
    TimePrecision.minute,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.minute,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.minute,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.minute, DateTimeLength.long, DateTimeAlignment.auto, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.minute,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.minute,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.minute,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.minute, DateTimeLength.long, DateTimeAlignment.column, null):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.minute, DateTimeLength.long, null, YearStyle.auto):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.minute, DateTimeLength.long, null, YearStyle.full):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.minute, DateTimeLength.long, null, YearStyle.withEra):
      'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.minute, DateTimeLength.long, null, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.minute,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minute,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minute,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minute, DateTimeLength.medium, DateTimeAlignment.auto, null):
      'Mi., 18.06.2025',
  (
    TimePrecision.minute,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minute,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minute,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minute, DateTimeLength.medium, DateTimeAlignment.column, null):
      'Mi., 18.06.2025',
  (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.auto):
      'Mi., 18.06.2025',
  (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minute, DateTimeLength.medium, null, null): 'Mi., 18.06.2025',
  (
    TimePrecision.minute,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.minute,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minute,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minute, DateTimeLength.short, DateTimeAlignment.auto, null):
      'Mi., 18.06.25',
  (
    TimePrecision.minute,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.minute,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minute,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minute, DateTimeLength.short, DateTimeAlignment.column, null):
      'Mi., 18.06.25',
  (TimePrecision.minute, DateTimeLength.short, null, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.minute, DateTimeLength.short, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.minute, DateTimeLength.short, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minute, DateTimeLength.short, null, null): 'Mi., 18.06.25',
  (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minute, null, DateTimeAlignment.auto, null): 'Mi., 18.06.25',
  (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minute, null, DateTimeAlignment.column, null): 'Mi., 18.06.25',
  (TimePrecision.minute, null, null, YearStyle.auto): 'Mi., 18.06.25',
  (TimePrecision.minute, null, null, YearStyle.full): 'Mi., 18.06.2025',
  (TimePrecision.minute, null, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minute, null, null, null): 'Mi., 18.06.25',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    null,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.long,
    DateTimeAlignment.column,
    null,
  ): 'Mittwoch, 18. Juni 2025',
  (TimePrecision.minuteOptional, DateTimeLength.long, null, YearStyle.auto):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.minuteOptional, DateTimeLength.long, null, YearStyle.full):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.minuteOptional, DateTimeLength.long, null, YearStyle.withEra):
      'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.minuteOptional, DateTimeLength.long, null, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    null,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    null,
  ): 'Mi., 18.06.2025',
  (TimePrecision.minuteOptional, DateTimeLength.medium, null, YearStyle.auto):
      'Mi., 18.06.2025',
  (TimePrecision.minuteOptional, DateTimeLength.medium, null, YearStyle.full):
      'Mi., 18.06.2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.medium,
    null,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minuteOptional, DateTimeLength.medium, null, null):
      'Mi., 18.06.2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    null,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.minuteOptional,
    DateTimeLength.short,
    DateTimeAlignment.column,
    null,
  ): 'Mi., 18.06.25',
  (TimePrecision.minuteOptional, DateTimeLength.short, null, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.minuteOptional, DateTimeLength.short, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.minuteOptional, DateTimeLength.short, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minuteOptional, DateTimeLength.short, null, null):
      'Mi., 18.06.25',
  (TimePrecision.minuteOptional, null, DateTimeAlignment.auto, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.minuteOptional, null, DateTimeAlignment.auto, YearStyle.full):
      'Mi., 18.06.2025',
  (
    TimePrecision.minuteOptional,
    null,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minuteOptional, null, DateTimeAlignment.auto, null):
      'Mi., 18.06.25',
  (
    TimePrecision.minuteOptional,
    null,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.minuteOptional,
    null,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.minuteOptional,
    null,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minuteOptional, null, DateTimeAlignment.column, null):
      'Mi., 18.06.25',
  (TimePrecision.minuteOptional, null, null, YearStyle.auto): 'Mi., 18.06.25',
  (TimePrecision.minuteOptional, null, null, YearStyle.full): 'Mi., 18.06.2025',
  (TimePrecision.minuteOptional, null, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.minuteOptional, null, null, null): 'Mi., 18.06.25',
  (
    TimePrecision.second,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.second,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.second,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.second, DateTimeLength.long, DateTimeAlignment.auto, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.second,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.second,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.second,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.second, DateTimeLength.long, DateTimeAlignment.column, null):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.second, DateTimeLength.long, null, YearStyle.auto):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.second, DateTimeLength.long, null, YearStyle.full):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.second, DateTimeLength.long, null, YearStyle.withEra):
      'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.second, DateTimeLength.long, null, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.second,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.second,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.second,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.second, DateTimeLength.medium, DateTimeAlignment.auto, null):
      'Mi., 18.06.2025',
  (
    TimePrecision.second,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.second,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.second,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.second, DateTimeLength.medium, DateTimeAlignment.column, null):
      'Mi., 18.06.2025',
  (TimePrecision.second, DateTimeLength.medium, null, YearStyle.auto):
      'Mi., 18.06.2025',
  (TimePrecision.second, DateTimeLength.medium, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.second, DateTimeLength.medium, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.second, DateTimeLength.medium, null, null): 'Mi., 18.06.2025',
  (
    TimePrecision.second,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.second,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.second,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.second, DateTimeLength.short, DateTimeAlignment.auto, null):
      'Mi., 18.06.25',
  (
    TimePrecision.second,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.second,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.second,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.second, DateTimeLength.short, DateTimeAlignment.column, null):
      'Mi., 18.06.25',
  (TimePrecision.second, DateTimeLength.short, null, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.second, DateTimeLength.short, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.second, DateTimeLength.short, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.second, DateTimeLength.short, null, null): 'Mi., 18.06.25',
  (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.second, null, DateTimeAlignment.auto, null): 'Mi., 18.06.25',
  (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.second, null, DateTimeAlignment.column, null): 'Mi., 18.06.25',
  (TimePrecision.second, null, null, YearStyle.auto): 'Mi., 18.06.25',
  (TimePrecision.second, null, null, YearStyle.full): 'Mi., 18.06.2025',
  (TimePrecision.second, null, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.second, null, null, null): 'Mi., 18.06.25',
  (
    TimePrecision.subsecond1,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.subsecond1, DateTimeLength.long, DateTimeAlignment.auto, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (
    TimePrecision.subsecond1,
    DateTimeLength.long,
    DateTimeAlignment.column,
    null,
  ): 'Mittwoch, 18. Juni 2025',
  (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.auto):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.full):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.withEra):
      'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.subsecond1, DateTimeLength.long, null, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.subsecond1,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    null,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.subsecond1,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    null,
  ): 'Mi., 18.06.2025',
  (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.auto):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond1, DateTimeLength.medium, null, null):
      'Mi., 18.06.2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.subsecond1,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.subsecond1,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    null,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.subsecond1,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.subsecond1,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond1,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.subsecond1,
    DateTimeLength.short,
    DateTimeAlignment.column,
    null,
  ): 'Mi., 18.06.25',
  (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond1, DateTimeLength.short, null, null): 'Mi., 18.06.25',
  (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond1, null, DateTimeAlignment.auto, null):
      'Mi., 18.06.25',
  (TimePrecision.subsecond1, null, DateTimeAlignment.column, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.subsecond1, null, DateTimeAlignment.column, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond1, null, DateTimeAlignment.column, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond1, null, DateTimeAlignment.column, null):
      'Mi., 18.06.25',
  (TimePrecision.subsecond1, null, null, YearStyle.auto): 'Mi., 18.06.25',
  (TimePrecision.subsecond1, null, null, YearStyle.full): 'Mi., 18.06.2025',
  (TimePrecision.subsecond1, null, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond1, null, null, null): 'Mi., 18.06.25',
  (
    TimePrecision.subsecond2,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.subsecond2, DateTimeLength.long, DateTimeAlignment.auto, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (
    TimePrecision.subsecond2,
    DateTimeLength.long,
    DateTimeAlignment.column,
    null,
  ): 'Mittwoch, 18. Juni 2025',
  (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.auto):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.full):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.withEra):
      'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.subsecond2, DateTimeLength.long, null, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.subsecond2,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    null,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.subsecond2,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    null,
  ): 'Mi., 18.06.2025',
  (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.auto):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond2, DateTimeLength.medium, null, null):
      'Mi., 18.06.2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.subsecond2,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.subsecond2,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    null,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.subsecond2,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.subsecond2,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond2,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.subsecond2,
    DateTimeLength.short,
    DateTimeAlignment.column,
    null,
  ): 'Mi., 18.06.25',
  (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond2, DateTimeLength.short, null, null): 'Mi., 18.06.25',
  (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond2, null, DateTimeAlignment.auto, null):
      'Mi., 18.06.25',
  (TimePrecision.subsecond2, null, DateTimeAlignment.column, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.subsecond2, null, DateTimeAlignment.column, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond2, null, DateTimeAlignment.column, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond2, null, DateTimeAlignment.column, null):
      'Mi., 18.06.25',
  (TimePrecision.subsecond2, null, null, YearStyle.auto): 'Mi., 18.06.25',
  (TimePrecision.subsecond2, null, null, YearStyle.full): 'Mi., 18.06.2025',
  (TimePrecision.subsecond2, null, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond2, null, null, null): 'Mi., 18.06.25',
  (
    TimePrecision.subsecond3,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.long,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.subsecond3, DateTimeLength.long, DateTimeAlignment.auto, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.long,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mittwoch, 18. Juni 2025 n. Chr.',
  (
    TimePrecision.subsecond3,
    DateTimeLength.long,
    DateTimeAlignment.column,
    null,
  ): 'Mittwoch, 18. Juni 2025',
  (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.auto):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.full):
      'Mittwoch, 18. Juni 2025',
  (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.withEra):
      'Mittwoch, 18. Juni 2025 n. Chr.',
  (TimePrecision.subsecond3, DateTimeLength.long, null, null):
      'Mittwoch, 18. Juni 2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.subsecond3,
    DateTimeLength.medium,
    DateTimeAlignment.auto,
    null,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.subsecond3,
    DateTimeLength.medium,
    DateTimeAlignment.column,
    null,
  ): 'Mi., 18.06.2025',
  (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.auto):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond3, DateTimeLength.medium, null, null):
      'Mi., 18.06.2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.subsecond3,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.subsecond3,
    DateTimeLength.short,
    DateTimeAlignment.auto,
    null,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.subsecond3,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.auto,
  ): 'Mi., 18.06.25',
  (
    TimePrecision.subsecond3,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.full,
  ): 'Mi., 18.06.2025',
  (
    TimePrecision.subsecond3,
    DateTimeLength.short,
    DateTimeAlignment.column,
    YearStyle.withEra,
  ): 'Mi., 18.06.2025 n. Chr.',
  (
    TimePrecision.subsecond3,
    DateTimeLength.short,
    DateTimeAlignment.column,
    null,
  ): 'Mi., 18.06.25',
  (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond3, DateTimeLength.short, null, null): 'Mi., 18.06.25',
  (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond3, null, DateTimeAlignment.auto, null):
      'Mi., 18.06.25',
  (TimePrecision.subsecond3, null, DateTimeAlignment.column, YearStyle.auto):
      'Mi., 18.06.25',
  (TimePrecision.subsecond3, null, DateTimeAlignment.column, YearStyle.full):
      'Mi., 18.06.2025',
  (TimePrecision.subsecond3, null, DateTimeAlignment.column, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond3, null, DateTimeAlignment.column, null):
      'Mi., 18.06.25',
  (TimePrecision.subsecond3, null, null, YearStyle.auto): 'Mi., 18.06.25',
  (TimePrecision.subsecond3, null, null, YearStyle.full): 'Mi., 18.06.2025',
  (TimePrecision.subsecond3, null, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (TimePrecision.subsecond3, null, null, null): 'Mi., 18.06.25',
  (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.auto):
      'Mittwoch, 18. Juni 2025',
  (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.full):
      'Mittwoch, 18. Juni 2025',
  (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.withEra):
      'Mittwoch, 18. Juni 2025 n. Chr.',
  (null, DateTimeLength.long, DateTimeAlignment.auto, null):
      'Mittwoch, 18. Juni 2025',
  (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.auto):
      'Mittwoch, 18. Juni 2025',
  (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.full):
      'Mittwoch, 18. Juni 2025',
  (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.withEra):
      'Mittwoch, 18. Juni 2025 n. Chr.',
  (null, DateTimeLength.long, DateTimeAlignment.column, null):
      'Mittwoch, 18. Juni 2025',
  (null, DateTimeLength.long, null, YearStyle.auto): 'Mittwoch, 18. Juni 2025',
  (null, DateTimeLength.long, null, YearStyle.full): 'Mittwoch, 18. Juni 2025',
  (null, DateTimeLength.long, null, YearStyle.withEra):
      'Mittwoch, 18. Juni 2025 n. Chr.',
  (null, DateTimeLength.long, null, null): 'Mittwoch, 18. Juni 2025',
  (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.auto):
      'Mi., 18.06.2025',
  (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.full):
      'Mi., 18.06.2025',
  (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (null, DateTimeLength.medium, DateTimeAlignment.auto, null):
      'Mi., 18.06.2025',
  (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.auto):
      'Mi., 18.06.2025',
  (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.full):
      'Mi., 18.06.2025',
  (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (null, DateTimeLength.medium, DateTimeAlignment.column, null):
      'Mi., 18.06.2025',
  (null, DateTimeLength.medium, null, YearStyle.auto): 'Mi., 18.06.2025',
  (null, DateTimeLength.medium, null, YearStyle.full): 'Mi., 18.06.2025',
  (null, DateTimeLength.medium, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (null, DateTimeLength.medium, null, null): 'Mi., 18.06.2025',
  (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.auto):
      'Mi., 18.06.25',
  (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.full):
      'Mi., 18.06.2025',
  (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (null, DateTimeLength.short, DateTimeAlignment.auto, null): 'Mi., 18.06.25',
  (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.auto):
      'Mi., 18.06.25',
  (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.full):
      'Mi., 18.06.2025',
  (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (null, DateTimeLength.short, DateTimeAlignment.column, null): 'Mi., 18.06.25',
  (null, DateTimeLength.short, null, YearStyle.auto): 'Mi., 18.06.25',
  (null, DateTimeLength.short, null, YearStyle.full): 'Mi., 18.06.2025',
  (null, DateTimeLength.short, null, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (null, DateTimeLength.short, null, null): 'Mi., 18.06.25',
  (null, null, DateTimeAlignment.auto, YearStyle.auto): 'Mi., 18.06.25',
  (null, null, DateTimeAlignment.auto, YearStyle.full): 'Mi., 18.06.2025',
  (null, null, DateTimeAlignment.auto, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (null, null, DateTimeAlignment.auto, null): 'Mi., 18.06.25',
  (null, null, DateTimeAlignment.column, YearStyle.auto): 'Mi., 18.06.25',
  (null, null, DateTimeAlignment.column, YearStyle.full): 'Mi., 18.06.2025',
  (null, null, DateTimeAlignment.column, YearStyle.withEra):
      'Mi., 18.06.2025 n. Chr.',
  (null, null, DateTimeAlignment.column, null): 'Mi., 18.06.25',
  (null, null, null, YearStyle.auto): 'Mi., 18.06.25',
  (null, null, null, YearStyle.full): 'Mi., 18.06.2025',
  (null, null, null, YearStyle.withEra): 'Mi., 18.06.2025 n. Chr.',
  (null, null, null, null): 'Mi., 18.06.25',
};
