// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:intl4x/datetime_format.dart';

// Generated content: Do not edit this file manually.
// Regenerate by running `dart run test/tools/regenerate_conformance_data.dart`

final tOptions = {
  'en-US': {
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2 PM',
    (TimePrecision.hour, DateTimeLength.long, DateTimeAlignment.auto, null):
        '2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02 PM',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02 PM',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02 PM',
    (TimePrecision.hour, DateTimeLength.long, DateTimeAlignment.column, null):
        '02 PM',
    (TimePrecision.hour, DateTimeLength.long, null, YearStyle.auto): '2 PM',
    (TimePrecision.hour, DateTimeLength.long, null, YearStyle.full): '2 PM',
    (TimePrecision.hour, DateTimeLength.long, null, YearStyle.withEra): '2 PM',
    (TimePrecision.hour, DateTimeLength.long, null, null): '2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2 PM',
    (TimePrecision.hour, DateTimeLength.medium, DateTimeAlignment.auto, null):
        '2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02 PM',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02 PM',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02 PM',
    (TimePrecision.hour, DateTimeLength.medium, DateTimeAlignment.column, null):
        '02 PM',
    (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.auto): '2 PM',
    (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.full): '2 PM',
    (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.withEra):
        '2 PM',
    (TimePrecision.hour, DateTimeLength.medium, null, null): '2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2 PM',
    (TimePrecision.hour, DateTimeLength.short, DateTimeAlignment.auto, null):
        '2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02 PM',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02 PM',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02 PM',
    (TimePrecision.hour, DateTimeLength.short, DateTimeAlignment.column, null):
        '02 PM',
    (TimePrecision.hour, DateTimeLength.short, null, YearStyle.auto): '2 PM',
    (TimePrecision.hour, DateTimeLength.short, null, YearStyle.full): '2 PM',
    (TimePrecision.hour, DateTimeLength.short, null, YearStyle.withEra): '2 PM',
    (TimePrecision.hour, DateTimeLength.short, null, null): '2 PM',
    (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.auto): '2 PM',
    (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.full): '2 PM',
    (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.withEra):
        '2 PM',
    (TimePrecision.hour, null, DateTimeAlignment.auto, null): '2 PM',
    (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.auto):
        '02 PM',
    (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.full):
        '02 PM',
    (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.withEra):
        '02 PM',
    (TimePrecision.hour, null, DateTimeAlignment.column, null): '02 PM',
    (TimePrecision.hour, null, null, YearStyle.auto): '2 PM',
    (TimePrecision.hour, null, null, YearStyle.full): '2 PM',
    (TimePrecision.hour, null, null, YearStyle.withEra): '2 PM',
    (TimePrecision.hour, null, null, null): '2 PM',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30 PM',
    (TimePrecision.minute, DateTimeLength.long, DateTimeAlignment.auto, null):
        '2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30 PM',
    (TimePrecision.minute, DateTimeLength.long, DateTimeAlignment.column, null):
        '02:30 PM',
    (TimePrecision.minute, DateTimeLength.long, null, YearStyle.auto):
        '2:30 PM',
    (TimePrecision.minute, DateTimeLength.long, null, YearStyle.full):
        '2:30 PM',
    (TimePrecision.minute, DateTimeLength.long, null, YearStyle.withEra):
        '2:30 PM',
    (TimePrecision.minute, DateTimeLength.long, null, null): '2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30 PM',
    (TimePrecision.minute, DateTimeLength.medium, DateTimeAlignment.auto, null):
        '2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '02:30 PM',
    (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.auto):
        '2:30 PM',
    (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.full):
        '2:30 PM',
    (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.withEra):
        '2:30 PM',
    (TimePrecision.minute, DateTimeLength.medium, null, null): '2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30 PM',
    (TimePrecision.minute, DateTimeLength.short, DateTimeAlignment.auto, null):
        '2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '02:30 PM',
    (TimePrecision.minute, DateTimeLength.short, null, YearStyle.auto):
        '2:30 PM',
    (TimePrecision.minute, DateTimeLength.short, null, YearStyle.full):
        '2:30 PM',
    (TimePrecision.minute, DateTimeLength.short, null, YearStyle.withEra):
        '2:30 PM',
    (TimePrecision.minute, DateTimeLength.short, null, null): '2:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.auto):
        '2:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.full):
        '2:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.withEra):
        '2:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.auto, null): '2:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.auto):
        '02:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.full):
        '02:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.withEra):
        '02:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.column, null): '02:30 PM',
    (TimePrecision.minute, null, null, YearStyle.auto): '2:30 PM',
    (TimePrecision.minute, null, null, YearStyle.full): '2:30 PM',
    (TimePrecision.minute, null, null, YearStyle.withEra): '2:30 PM',
    (TimePrecision.minute, null, null, null): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): '02:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.long, null, YearStyle.auto):
        '2:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.long, null, YearStyle.full):
        '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      null,
      YearStyle.withEra,
    ): '2:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.long, null, null): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '02:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.medium, null, YearStyle.auto):
        '2:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.medium, null, YearStyle.full):
        '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      null,
      YearStyle.withEra,
    ): '2:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.medium, null, null):
        '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '02:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.short, null, YearStyle.auto):
        '2:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.short, null, YearStyle.full):
        '2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      null,
      YearStyle.withEra,
    ): '2:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.short, null, null): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30 PM',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30 PM',
    (TimePrecision.minuteOptional, null, DateTimeAlignment.auto, null):
        '2:30 PM',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30 PM',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30 PM',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30 PM',
    (TimePrecision.minuteOptional, null, DateTimeAlignment.column, null):
        '02:30 PM',
    (TimePrecision.minuteOptional, null, null, YearStyle.auto): '2:30 PM',
    (TimePrecision.minuteOptional, null, null, YearStyle.full): '2:30 PM',
    (TimePrecision.minuteOptional, null, null, YearStyle.withEra): '2:30 PM',
    (TimePrecision.minuteOptional, null, null, null): '2:30 PM',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30:45 PM',
    (TimePrecision.second, DateTimeLength.long, DateTimeAlignment.auto, null):
        '2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45 PM',
    (TimePrecision.second, DateTimeLength.long, DateTimeAlignment.column, null):
        '02:30:45 PM',
    (TimePrecision.second, DateTimeLength.long, null, YearStyle.auto):
        '2:30:45 PM',
    (TimePrecision.second, DateTimeLength.long, null, YearStyle.full):
        '2:30:45 PM',
    (TimePrecision.second, DateTimeLength.long, null, YearStyle.withEra):
        '2:30:45 PM',
    (TimePrecision.second, DateTimeLength.long, null, null): '2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30:45 PM',
    (TimePrecision.second, DateTimeLength.medium, DateTimeAlignment.auto, null):
        '2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '02:30:45 PM',
    (TimePrecision.second, DateTimeLength.medium, null, YearStyle.auto):
        '2:30:45 PM',
    (TimePrecision.second, DateTimeLength.medium, null, YearStyle.full):
        '2:30:45 PM',
    (TimePrecision.second, DateTimeLength.medium, null, YearStyle.withEra):
        '2:30:45 PM',
    (TimePrecision.second, DateTimeLength.medium, null, null): '2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30:45 PM',
    (TimePrecision.second, DateTimeLength.short, DateTimeAlignment.auto, null):
        '2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '02:30:45 PM',
    (TimePrecision.second, DateTimeLength.short, null, YearStyle.auto):
        '2:30:45 PM',
    (TimePrecision.second, DateTimeLength.short, null, YearStyle.full):
        '2:30:45 PM',
    (TimePrecision.second, DateTimeLength.short, null, YearStyle.withEra):
        '2:30:45 PM',
    (TimePrecision.second, DateTimeLength.short, null, null): '2:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.auto):
        '2:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.full):
        '2:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.withEra):
        '2:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.auto, null): '2:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.auto):
        '02:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.full):
        '02:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.withEra):
        '02:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.column, null): '02:30:45 PM',
    (TimePrecision.second, null, null, YearStyle.auto): '2:30:45 PM',
    (TimePrecision.second, null, null, YearStyle.full): '2:30:45 PM',
    (TimePrecision.second, null, null, YearStyle.withEra): '2:30:45 PM',
    (TimePrecision.second, null, null, null): '2:30:45 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): '02:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.auto):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.full):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.withEra):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.long, null, null): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '02:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.auto):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.full):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.withEra):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, null):
        '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '02:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.auto):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.full):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.withEra):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.short, null, null):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.auto):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.full):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.withEra):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, null):
        '2:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.column, YearStyle.auto):
        '02:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.column, YearStyle.full):
        '02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.column, null):
        '02:30:45.1 PM',
    (TimePrecision.subsecond1, null, null, YearStyle.auto): '2:30:45.1 PM',
    (TimePrecision.subsecond1, null, null, YearStyle.full): '2:30:45.1 PM',
    (TimePrecision.subsecond1, null, null, YearStyle.withEra): '2:30:45.1 PM',
    (TimePrecision.subsecond1, null, null, null): '2:30:45.1 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): '02:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.auto):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.full):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.withEra):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.long, null, null):
        '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '02:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.auto):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.full):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.withEra):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, null):
        '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '02:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.auto):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.full):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.withEra):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.short, null, null):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.auto):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.full):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.withEra):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, null):
        '2:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.column, YearStyle.auto):
        '02:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.column, YearStyle.full):
        '02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.column, null):
        '02:30:45.12 PM',
    (TimePrecision.subsecond2, null, null, YearStyle.auto): '2:30:45.12 PM',
    (TimePrecision.subsecond2, null, null, YearStyle.full): '2:30:45.12 PM',
    (TimePrecision.subsecond2, null, null, YearStyle.withEra): '2:30:45.12 PM',
    (TimePrecision.subsecond2, null, null, null): '2:30:45.12 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): '02:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.auto):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.full):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.withEra):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.long, null, null):
        '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '02:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.auto):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.full):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.withEra):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, null):
        '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '02:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.auto):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.full):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.withEra):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.short, null, null):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.auto):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.full):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.withEra):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, null):
        '2:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.column, YearStyle.auto):
        '02:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.column, YearStyle.full):
        '02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '02:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.column, null):
        '02:30:45.123 PM',
    (TimePrecision.subsecond3, null, null, YearStyle.auto): '2:30:45.123 PM',
    (TimePrecision.subsecond3, null, null, YearStyle.full): '2:30:45.123 PM',
    (TimePrecision.subsecond3, null, null, YearStyle.withEra): '2:30:45.123 PM',
    (TimePrecision.subsecond3, null, null, null): '2:30:45.123 PM',
    (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.auto):
        '2:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.full):
        '2:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.withEra):
        '2:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.auto, null): '2:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.auto):
        '02:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.full):
        '02:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.withEra):
        '02:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.column, null): '02:30:45 PM',
    (null, DateTimeLength.long, null, YearStyle.auto): '2:30:45 PM',
    (null, DateTimeLength.long, null, YearStyle.full): '2:30:45 PM',
    (null, DateTimeLength.long, null, YearStyle.withEra): '2:30:45 PM',
    (null, DateTimeLength.long, null, null): '2:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.auto):
        '2:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.full):
        '2:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.withEra):
        '2:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, null): '2:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.auto):
        '02:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.full):
        '02:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.withEra):
        '02:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.column, null):
        '02:30:45 PM',
    (null, DateTimeLength.medium, null, YearStyle.auto): '2:30:45 PM',
    (null, DateTimeLength.medium, null, YearStyle.full): '2:30:45 PM',
    (null, DateTimeLength.medium, null, YearStyle.withEra): '2:30:45 PM',
    (null, DateTimeLength.medium, null, null): '2:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.auto):
        '2:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.full):
        '2:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.withEra):
        '2:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.auto, null): '2:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.auto):
        '02:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.full):
        '02:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.withEra):
        '02:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.column, null): '02:30:45 PM',
    (null, DateTimeLength.short, null, YearStyle.auto): '2:30:45 PM',
    (null, DateTimeLength.short, null, YearStyle.full): '2:30:45 PM',
    (null, DateTimeLength.short, null, YearStyle.withEra): '2:30:45 PM',
    (null, DateTimeLength.short, null, null): '2:30:45 PM',
    (null, null, DateTimeAlignment.auto, YearStyle.auto): '2:30:45 PM',
    (null, null, DateTimeAlignment.auto, YearStyle.full): '2:30:45 PM',
    (null, null, DateTimeAlignment.auto, YearStyle.withEra): '2:30:45 PM',
    (null, null, DateTimeAlignment.auto, null): '2:30:45 PM',
    (null, null, DateTimeAlignment.column, YearStyle.auto): '02:30:45 PM',
    (null, null, DateTimeAlignment.column, YearStyle.full): '02:30:45 PM',
    (null, null, DateTimeAlignment.column, YearStyle.withEra): '02:30:45 PM',
    (null, null, DateTimeAlignment.column, null): '02:30:45 PM',
    (null, null, null, YearStyle.auto): '2:30:45 PM',
    (null, null, null, YearStyle.full): '2:30:45 PM',
    (null, null, null, YearStyle.withEra): '2:30:45 PM',
    (null, null, null, null): '2:30:45 PM',
  },
  'de-DE': {
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14 Uhr',
    (TimePrecision.hour, DateTimeLength.long, DateTimeAlignment.auto, null):
        '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14 Uhr',
    (TimePrecision.hour, DateTimeLength.long, DateTimeAlignment.column, null):
        '14 Uhr',
    (TimePrecision.hour, DateTimeLength.long, null, YearStyle.auto): '14 Uhr',
    (TimePrecision.hour, DateTimeLength.long, null, YearStyle.full): '14 Uhr',
    (TimePrecision.hour, DateTimeLength.long, null, YearStyle.withEra):
        '14 Uhr',
    (TimePrecision.hour, DateTimeLength.long, null, null): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14 Uhr',
    (TimePrecision.hour, DateTimeLength.medium, DateTimeAlignment.auto, null):
        '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14 Uhr',
    (TimePrecision.hour, DateTimeLength.medium, DateTimeAlignment.column, null):
        '14 Uhr',
    (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.auto): '14 Uhr',
    (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.full): '14 Uhr',
    (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.withEra):
        '14 Uhr',
    (TimePrecision.hour, DateTimeLength.medium, null, null): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14 Uhr',
    (TimePrecision.hour, DateTimeLength.short, DateTimeAlignment.auto, null):
        '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14 Uhr',
    (TimePrecision.hour, DateTimeLength.short, DateTimeAlignment.column, null):
        '14 Uhr',
    (TimePrecision.hour, DateTimeLength.short, null, YearStyle.auto): '14 Uhr',
    (TimePrecision.hour, DateTimeLength.short, null, YearStyle.full): '14 Uhr',
    (TimePrecision.hour, DateTimeLength.short, null, YearStyle.withEra):
        '14 Uhr',
    (TimePrecision.hour, DateTimeLength.short, null, null): '14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.auto):
        '14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.full):
        '14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.withEra):
        '14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.auto, null): '14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.auto):
        '14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.full):
        '14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.withEra):
        '14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.column, null): '14 Uhr',
    (TimePrecision.hour, null, null, YearStyle.auto): '14 Uhr',
    (TimePrecision.hour, null, null, YearStyle.full): '14 Uhr',
    (TimePrecision.hour, null, null, YearStyle.withEra): '14 Uhr',
    (TimePrecision.hour, null, null, null): '14 Uhr',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30',
    (TimePrecision.minute, DateTimeLength.long, DateTimeAlignment.auto, null):
        '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30',
    (TimePrecision.minute, DateTimeLength.long, DateTimeAlignment.column, null):
        '14:30',
    (TimePrecision.minute, DateTimeLength.long, null, YearStyle.auto): '14:30',
    (TimePrecision.minute, DateTimeLength.long, null, YearStyle.full): '14:30',
    (TimePrecision.minute, DateTimeLength.long, null, YearStyle.withEra):
        '14:30',
    (TimePrecision.minute, DateTimeLength.long, null, null): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30',
    (TimePrecision.minute, DateTimeLength.medium, DateTimeAlignment.auto, null):
        '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '14:30',
    (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.auto):
        '14:30',
    (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.full):
        '14:30',
    (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.withEra):
        '14:30',
    (TimePrecision.minute, DateTimeLength.medium, null, null): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30',
    (TimePrecision.minute, DateTimeLength.short, DateTimeAlignment.auto, null):
        '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '14:30',
    (TimePrecision.minute, DateTimeLength.short, null, YearStyle.auto): '14:30',
    (TimePrecision.minute, DateTimeLength.short, null, YearStyle.full): '14:30',
    (TimePrecision.minute, DateTimeLength.short, null, YearStyle.withEra):
        '14:30',
    (TimePrecision.minute, DateTimeLength.short, null, null): '14:30',
    (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.auto):
        '14:30',
    (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.full):
        '14:30',
    (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.withEra):
        '14:30',
    (TimePrecision.minute, null, DateTimeAlignment.auto, null): '14:30',
    (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.auto):
        '14:30',
    (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.full):
        '14:30',
    (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.withEra):
        '14:30',
    (TimePrecision.minute, null, DateTimeAlignment.column, null): '14:30',
    (TimePrecision.minute, null, null, YearStyle.auto): '14:30',
    (TimePrecision.minute, null, null, YearStyle.full): '14:30',
    (TimePrecision.minute, null, null, YearStyle.withEra): '14:30',
    (TimePrecision.minute, null, null, null): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): '14:30',
    (TimePrecision.minuteOptional, DateTimeLength.long, null, YearStyle.auto):
        '14:30',
    (TimePrecision.minuteOptional, DateTimeLength.long, null, YearStyle.full):
        '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      null,
      YearStyle.withEra,
    ): '14:30',
    (TimePrecision.minuteOptional, DateTimeLength.long, null, null): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '14:30',
    (TimePrecision.minuteOptional, DateTimeLength.medium, null, YearStyle.auto):
        '14:30',
    (TimePrecision.minuteOptional, DateTimeLength.medium, null, YearStyle.full):
        '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      null,
      YearStyle.withEra,
    ): '14:30',
    (TimePrecision.minuteOptional, DateTimeLength.medium, null, null): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '14:30',
    (TimePrecision.minuteOptional, DateTimeLength.short, null, YearStyle.auto):
        '14:30',
    (TimePrecision.minuteOptional, DateTimeLength.short, null, YearStyle.full):
        '14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      null,
      YearStyle.withEra,
    ): '14:30',
    (TimePrecision.minuteOptional, DateTimeLength.short, null, null): '14:30',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30',
    (TimePrecision.minuteOptional, null, DateTimeAlignment.auto, null): '14:30',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30',
    (TimePrecision.minuteOptional, null, DateTimeAlignment.column, null):
        '14:30',
    (TimePrecision.minuteOptional, null, null, YearStyle.auto): '14:30',
    (TimePrecision.minuteOptional, null, null, YearStyle.full): '14:30',
    (TimePrecision.minuteOptional, null, null, YearStyle.withEra): '14:30',
    (TimePrecision.minuteOptional, null, null, null): '14:30',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30:45',
    (TimePrecision.second, DateTimeLength.long, DateTimeAlignment.auto, null):
        '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45',
    (TimePrecision.second, DateTimeLength.long, DateTimeAlignment.column, null):
        '14:30:45',
    (TimePrecision.second, DateTimeLength.long, null, YearStyle.auto):
        '14:30:45',
    (TimePrecision.second, DateTimeLength.long, null, YearStyle.full):
        '14:30:45',
    (TimePrecision.second, DateTimeLength.long, null, YearStyle.withEra):
        '14:30:45',
    (TimePrecision.second, DateTimeLength.long, null, null): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30:45',
    (TimePrecision.second, DateTimeLength.medium, DateTimeAlignment.auto, null):
        '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '14:30:45',
    (TimePrecision.second, DateTimeLength.medium, null, YearStyle.auto):
        '14:30:45',
    (TimePrecision.second, DateTimeLength.medium, null, YearStyle.full):
        '14:30:45',
    (TimePrecision.second, DateTimeLength.medium, null, YearStyle.withEra):
        '14:30:45',
    (TimePrecision.second, DateTimeLength.medium, null, null): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30:45',
    (TimePrecision.second, DateTimeLength.short, DateTimeAlignment.auto, null):
        '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '14:30:45',
    (TimePrecision.second, DateTimeLength.short, null, YearStyle.auto):
        '14:30:45',
    (TimePrecision.second, DateTimeLength.short, null, YearStyle.full):
        '14:30:45',
    (TimePrecision.second, DateTimeLength.short, null, YearStyle.withEra):
        '14:30:45',
    (TimePrecision.second, DateTimeLength.short, null, null): '14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.auto):
        '14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.full):
        '14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.withEra):
        '14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.auto, null): '14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.auto):
        '14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.full):
        '14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.withEra):
        '14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.column, null): '14:30:45',
    (TimePrecision.second, null, null, YearStyle.auto): '14:30:45',
    (TimePrecision.second, null, null, YearStyle.full): '14:30:45',
    (TimePrecision.second, null, null, YearStyle.withEra): '14:30:45',
    (TimePrecision.second, null, null, null): '14:30:45',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): '14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.auto):
        '14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.full):
        '14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.withEra):
        '14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.long, null, null): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.auto):
        '14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.full):
        '14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.withEra):
        '14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, null): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.auto):
        '14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.full):
        '14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.withEra):
        '14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.short, null, null): '14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.auto):
        '14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.full):
        '14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.withEra):
        '14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, null):
        '14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.column, YearStyle.auto):
        '14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.column, YearStyle.full):
        '14:30:45,1',
    (
      TimePrecision.subsecond1,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.column, null):
        '14:30:45,1',
    (TimePrecision.subsecond1, null, null, YearStyle.auto): '14:30:45,1',
    (TimePrecision.subsecond1, null, null, YearStyle.full): '14:30:45,1',
    (TimePrecision.subsecond1, null, null, YearStyle.withEra): '14:30:45,1',
    (TimePrecision.subsecond1, null, null, null): '14:30:45,1',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): '14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.auto):
        '14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.full):
        '14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.withEra):
        '14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.long, null, null): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.auto):
        '14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.full):
        '14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.withEra):
        '14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, null):
        '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.auto):
        '14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.full):
        '14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.withEra):
        '14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.short, null, null): '14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.auto):
        '14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.full):
        '14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.withEra):
        '14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, null):
        '14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.column, YearStyle.auto):
        '14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.column, YearStyle.full):
        '14:30:45,12',
    (
      TimePrecision.subsecond2,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.column, null):
        '14:30:45,12',
    (TimePrecision.subsecond2, null, null, YearStyle.auto): '14:30:45,12',
    (TimePrecision.subsecond2, null, null, YearStyle.full): '14:30:45,12',
    (TimePrecision.subsecond2, null, null, YearStyle.withEra): '14:30:45,12',
    (TimePrecision.subsecond2, null, null, null): '14:30:45,12',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): '14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.auto):
        '14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.full):
        '14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.withEra):
        '14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.long, null, null): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.auto):
        '14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.full):
        '14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.withEra):
        '14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, null):
        '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.auto):
        '14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.full):
        '14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.withEra):
        '14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.short, null, null):
        '14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.auto):
        '14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.full):
        '14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.withEra):
        '14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, null):
        '14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.column, YearStyle.auto):
        '14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.column, YearStyle.full):
        '14:30:45,123',
    (
      TimePrecision.subsecond3,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.column, null):
        '14:30:45,123',
    (TimePrecision.subsecond3, null, null, YearStyle.auto): '14:30:45,123',
    (TimePrecision.subsecond3, null, null, YearStyle.full): '14:30:45,123',
    (TimePrecision.subsecond3, null, null, YearStyle.withEra): '14:30:45,123',
    (TimePrecision.subsecond3, null, null, null): '14:30:45,123',
    (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.auto):
        '14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.full):
        '14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.withEra):
        '14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.auto, null): '14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.auto):
        '14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.full):
        '14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.withEra):
        '14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.column, null): '14:30:45',
    (null, DateTimeLength.long, null, YearStyle.auto): '14:30:45',
    (null, DateTimeLength.long, null, YearStyle.full): '14:30:45',
    (null, DateTimeLength.long, null, YearStyle.withEra): '14:30:45',
    (null, DateTimeLength.long, null, null): '14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.auto):
        '14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.full):
        '14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.withEra):
        '14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, null): '14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.auto):
        '14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.full):
        '14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.withEra):
        '14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.column, null): '14:30:45',
    (null, DateTimeLength.medium, null, YearStyle.auto): '14:30:45',
    (null, DateTimeLength.medium, null, YearStyle.full): '14:30:45',
    (null, DateTimeLength.medium, null, YearStyle.withEra): '14:30:45',
    (null, DateTimeLength.medium, null, null): '14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.auto):
        '14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.full):
        '14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.withEra):
        '14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.auto, null): '14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.auto):
        '14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.full):
        '14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.withEra):
        '14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.column, null): '14:30:45',
    (null, DateTimeLength.short, null, YearStyle.auto): '14:30:45',
    (null, DateTimeLength.short, null, YearStyle.full): '14:30:45',
    (null, DateTimeLength.short, null, YearStyle.withEra): '14:30:45',
    (null, DateTimeLength.short, null, null): '14:30:45',
    (null, null, DateTimeAlignment.auto, YearStyle.auto): '14:30:45',
    (null, null, DateTimeAlignment.auto, YearStyle.full): '14:30:45',
    (null, null, DateTimeAlignment.auto, YearStyle.withEra): '14:30:45',
    (null, null, DateTimeAlignment.auto, null): '14:30:45',
    (null, null, DateTimeAlignment.column, YearStyle.auto): '14:30:45',
    (null, null, DateTimeAlignment.column, YearStyle.full): '14:30:45',
    (null, null, DateTimeAlignment.column, YearStyle.withEra): '14:30:45',
    (null, null, DateTimeAlignment.column, null): '14:30:45',
    (null, null, null, YearStyle.auto): '14:30:45',
    (null, null, null, YearStyle.full): '14:30:45',
    (null, null, null, YearStyle.withEra): '14:30:45',
    (null, null, null, null): '14:30:45',
  },
};
