// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:intl4x/datetime_format.dart';

// Generated content: Do not edit this file manually.
// Regenerate by running `dart run test/tools/regenerate_conformance_data.dart`

final ymdtOptions = {
  'en-US': {
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'June 8, 2025 at 2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'June 8, 2025 at 2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'June 8, 2025 AD at 2 PM',
    (TimePrecision.hour, DateTimeLength.long, DateTimeAlignment.auto, null):
        'June 8, 2025 at 2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'June 08, 2025 at 02 PM',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'June 08, 2025 at 02 PM',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'June 08, 2025 AD at 02 PM',
    (TimePrecision.hour, DateTimeLength.long, DateTimeAlignment.column, null):
        'June 08, 2025 at 02 PM',
    (TimePrecision.hour, DateTimeLength.long, null, YearStyle.auto):
        'June 8, 2025 at 2 PM',
    (TimePrecision.hour, DateTimeLength.long, null, YearStyle.full):
        'June 8, 2025 at 2 PM',
    (TimePrecision.hour, DateTimeLength.long, null, YearStyle.withEra):
        'June 8, 2025 AD at 2 PM',
    (TimePrecision.hour, DateTimeLength.long, null, null):
        'June 8, 2025 at 2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'Jun 8, 2025, 2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'Jun 8, 2025, 2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'Jun 8, 2025 AD, 2 PM',
    (TimePrecision.hour, DateTimeLength.medium, DateTimeAlignment.auto, null):
        'Jun 8, 2025, 2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'Jun 08, 2025, 02 PM',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'Jun 08, 2025, 02 PM',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'Jun 08, 2025 AD, 02 PM',
    (TimePrecision.hour, DateTimeLength.medium, DateTimeAlignment.column, null):
        'Jun 08, 2025, 02 PM',
    (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.auto):
        'Jun 8, 2025, 2 PM',
    (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.full):
        'Jun 8, 2025, 2 PM',
    (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.withEra):
        'Jun 8, 2025 AD, 2 PM',
    (TimePrecision.hour, DateTimeLength.medium, null, null):
        'Jun 8, 2025, 2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '6/8/25, 2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '6/8/2025, 2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '6/8/2025 AD, 2 PM',
    (TimePrecision.hour, DateTimeLength.short, DateTimeAlignment.auto, null):
        '6/8/25, 2 PM',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '06/08/25, 02 PM',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '06/08/2025, 02 PM',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '06/08/2025 AD, 02 PM',
    (TimePrecision.hour, DateTimeLength.short, DateTimeAlignment.column, null):
        '06/08/25, 02 PM',
    (TimePrecision.hour, DateTimeLength.short, null, YearStyle.auto):
        '6/8/25, 2 PM',
    (TimePrecision.hour, DateTimeLength.short, null, YearStyle.full):
        '6/8/2025, 2 PM',
    (TimePrecision.hour, DateTimeLength.short, null, YearStyle.withEra):
        '6/8/2025 AD, 2 PM',
    (TimePrecision.hour, DateTimeLength.short, null, null): '6/8/25, 2 PM',
    (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.auto):
        '6/8/25, 2 PM',
    (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.full):
        '6/8/2025, 2 PM',
    (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.withEra):
        '6/8/2025 AD, 2 PM',
    (TimePrecision.hour, null, DateTimeAlignment.auto, null): '6/8/25, 2 PM',
    (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.auto):
        '06/08/25, 02 PM',
    (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.full):
        '06/08/2025, 02 PM',
    (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.withEra):
        '06/08/2025 AD, 02 PM',
    (TimePrecision.hour, null, DateTimeAlignment.column, null):
        '06/08/25, 02 PM',
    (TimePrecision.hour, null, null, YearStyle.auto): '6/8/25, 2 PM',
    (TimePrecision.hour, null, null, YearStyle.full): '6/8/2025, 2 PM',
    (TimePrecision.hour, null, null, YearStyle.withEra): '6/8/2025 AD, 2 PM',
    (TimePrecision.hour, null, null, null): '6/8/25, 2 PM',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'June 8, 2025 at 2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'June 8, 2025 at 2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'June 8, 2025 AD at 2:30 PM',
    (TimePrecision.minute, DateTimeLength.long, DateTimeAlignment.auto, null):
        'June 8, 2025 at 2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'June 08, 2025 at 02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'June 08, 2025 at 02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'June 08, 2025 AD at 02:30 PM',
    (TimePrecision.minute, DateTimeLength.long, DateTimeAlignment.column, null):
        'June 08, 2025 at 02:30 PM',
    (TimePrecision.minute, DateTimeLength.long, null, YearStyle.auto):
        'June 8, 2025 at 2:30 PM',
    (TimePrecision.minute, DateTimeLength.long, null, YearStyle.full):
        'June 8, 2025 at 2:30 PM',
    (TimePrecision.minute, DateTimeLength.long, null, YearStyle.withEra):
        'June 8, 2025 AD at 2:30 PM',
    (TimePrecision.minute, DateTimeLength.long, null, null):
        'June 8, 2025 at 2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'Jun 8, 2025, 2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'Jun 8, 2025, 2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'Jun 8, 2025 AD, 2:30 PM',
    (TimePrecision.minute, DateTimeLength.medium, DateTimeAlignment.auto, null):
        'Jun 8, 2025, 2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'Jun 08, 2025, 02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'Jun 08, 2025, 02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'Jun 08, 2025 AD, 02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): 'Jun 08, 2025, 02:30 PM',
    (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.auto):
        'Jun 8, 2025, 2:30 PM',
    (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.full):
        'Jun 8, 2025, 2:30 PM',
    (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.withEra):
        'Jun 8, 2025 AD, 2:30 PM',
    (TimePrecision.minute, DateTimeLength.medium, null, null):
        'Jun 8, 2025, 2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '6/8/25, 2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '6/8/2025, 2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '6/8/2025 AD, 2:30 PM',
    (TimePrecision.minute, DateTimeLength.short, DateTimeAlignment.auto, null):
        '6/8/25, 2:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '06/08/25, 02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '06/08/2025, 02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '06/08/2025 AD, 02:30 PM',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '06/08/25, 02:30 PM',
    (TimePrecision.minute, DateTimeLength.short, null, YearStyle.auto):
        '6/8/25, 2:30 PM',
    (TimePrecision.minute, DateTimeLength.short, null, YearStyle.full):
        '6/8/2025, 2:30 PM',
    (TimePrecision.minute, DateTimeLength.short, null, YearStyle.withEra):
        '6/8/2025 AD, 2:30 PM',
    (TimePrecision.minute, DateTimeLength.short, null, null): '6/8/25, 2:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.auto):
        '6/8/25, 2:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.full):
        '6/8/2025, 2:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.withEra):
        '6/8/2025 AD, 2:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.auto, null):
        '6/8/25, 2:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.auto):
        '06/08/25, 02:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.full):
        '06/08/2025, 02:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.withEra):
        '06/08/2025 AD, 02:30 PM',
    (TimePrecision.minute, null, DateTimeAlignment.column, null):
        '06/08/25, 02:30 PM',
    (TimePrecision.minute, null, null, YearStyle.auto): '6/8/25, 2:30 PM',
    (TimePrecision.minute, null, null, YearStyle.full): '6/8/2025, 2:30 PM',
    (TimePrecision.minute, null, null, YearStyle.withEra):
        '6/8/2025 AD, 2:30 PM',
    (TimePrecision.minute, null, null, null): '6/8/25, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'June 8, 2025 at 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'June 8, 2025 at 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'June 8, 2025 AD at 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): 'June 8, 2025 at 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'June 08, 2025 at 02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'June 08, 2025 at 02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'June 08, 2025 AD at 02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): 'June 08, 2025 at 02:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.long, null, YearStyle.auto):
        'June 8, 2025 at 2:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.long, null, YearStyle.full):
        'June 8, 2025 at 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      null,
      YearStyle.withEra,
    ): 'June 8, 2025 AD at 2:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.long, null, null):
        'June 8, 2025 at 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'Jun 8, 2025, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'Jun 8, 2025, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'Jun 8, 2025 AD, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): 'Jun 8, 2025, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'Jun 08, 2025, 02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'Jun 08, 2025, 02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'Jun 08, 2025 AD, 02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): 'Jun 08, 2025, 02:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.medium, null, YearStyle.auto):
        'Jun 8, 2025, 2:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.medium, null, YearStyle.full):
        'Jun 8, 2025, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      null,
      YearStyle.withEra,
    ): 'Jun 8, 2025 AD, 2:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.medium, null, null):
        'Jun 8, 2025, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '6/8/25, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '6/8/2025, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '6/8/2025 AD, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '6/8/25, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '06/08/25, 02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '06/08/2025, 02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '06/08/2025 AD, 02:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '06/08/25, 02:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.short, null, YearStyle.auto):
        '6/8/25, 2:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.short, null, YearStyle.full):
        '6/8/2025, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      null,
      YearStyle.withEra,
    ): '6/8/2025 AD, 2:30 PM',
    (TimePrecision.minuteOptional, DateTimeLength.short, null, null):
        '6/8/25, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '6/8/25, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '6/8/2025, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '6/8/2025 AD, 2:30 PM',
    (TimePrecision.minuteOptional, null, DateTimeAlignment.auto, null):
        '6/8/25, 2:30 PM',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '06/08/25, 02:30 PM',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '06/08/2025, 02:30 PM',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '06/08/2025 AD, 02:30 PM',
    (TimePrecision.minuteOptional, null, DateTimeAlignment.column, null):
        '06/08/25, 02:30 PM',
    (TimePrecision.minuteOptional, null, null, YearStyle.auto):
        '6/8/25, 2:30 PM',
    (TimePrecision.minuteOptional, null, null, YearStyle.full):
        '6/8/2025, 2:30 PM',
    (TimePrecision.minuteOptional, null, null, YearStyle.withEra):
        '6/8/2025 AD, 2:30 PM',
    (TimePrecision.minuteOptional, null, null, null): '6/8/25, 2:30 PM',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'June 8, 2025 at 2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'June 8, 2025 at 2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'June 8, 2025 AD at 2:30:45 PM',
    (TimePrecision.second, DateTimeLength.long, DateTimeAlignment.auto, null):
        'June 8, 2025 at 2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'June 08, 2025 at 02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'June 08, 2025 at 02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'June 08, 2025 AD at 02:30:45 PM',
    (TimePrecision.second, DateTimeLength.long, DateTimeAlignment.column, null):
        'June 08, 2025 at 02:30:45 PM',
    (TimePrecision.second, DateTimeLength.long, null, YearStyle.auto):
        'June 8, 2025 at 2:30:45 PM',
    (TimePrecision.second, DateTimeLength.long, null, YearStyle.full):
        'June 8, 2025 at 2:30:45 PM',
    (TimePrecision.second, DateTimeLength.long, null, YearStyle.withEra):
        'June 8, 2025 AD at 2:30:45 PM',
    (TimePrecision.second, DateTimeLength.long, null, null):
        'June 8, 2025 at 2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'Jun 8, 2025, 2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'Jun 8, 2025, 2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'Jun 8, 2025 AD, 2:30:45 PM',
    (TimePrecision.second, DateTimeLength.medium, DateTimeAlignment.auto, null):
        'Jun 8, 2025, 2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'Jun 08, 2025, 02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'Jun 08, 2025, 02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'Jun 08, 2025 AD, 02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): 'Jun 08, 2025, 02:30:45 PM',
    (TimePrecision.second, DateTimeLength.medium, null, YearStyle.auto):
        'Jun 8, 2025, 2:30:45 PM',
    (TimePrecision.second, DateTimeLength.medium, null, YearStyle.full):
        'Jun 8, 2025, 2:30:45 PM',
    (TimePrecision.second, DateTimeLength.medium, null, YearStyle.withEra):
        'Jun 8, 2025 AD, 2:30:45 PM',
    (TimePrecision.second, DateTimeLength.medium, null, null):
        'Jun 8, 2025, 2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '6/8/25, 2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '6/8/2025, 2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '6/8/2025 AD, 2:30:45 PM',
    (TimePrecision.second, DateTimeLength.short, DateTimeAlignment.auto, null):
        '6/8/25, 2:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '06/08/25, 02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '06/08/2025, 02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '06/08/2025 AD, 02:30:45 PM',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '06/08/25, 02:30:45 PM',
    (TimePrecision.second, DateTimeLength.short, null, YearStyle.auto):
        '6/8/25, 2:30:45 PM',
    (TimePrecision.second, DateTimeLength.short, null, YearStyle.full):
        '6/8/2025, 2:30:45 PM',
    (TimePrecision.second, DateTimeLength.short, null, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45 PM',
    (TimePrecision.second, DateTimeLength.short, null, null):
        '6/8/25, 2:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.auto):
        '6/8/25, 2:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.full):
        '6/8/2025, 2:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.auto, null):
        '6/8/25, 2:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.auto):
        '06/08/25, 02:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.full):
        '06/08/2025, 02:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.withEra):
        '06/08/2025 AD, 02:30:45 PM',
    (TimePrecision.second, null, DateTimeAlignment.column, null):
        '06/08/25, 02:30:45 PM',
    (TimePrecision.second, null, null, YearStyle.auto): '6/8/25, 2:30:45 PM',
    (TimePrecision.second, null, null, YearStyle.full): '6/8/2025, 2:30:45 PM',
    (TimePrecision.second, null, null, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45 PM',
    (TimePrecision.second, null, null, null): '6/8/25, 2:30:45 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'June 8, 2025 at 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'June 8, 2025 at 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'June 8, 2025 AD at 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): 'June 8, 2025 at 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'June 08, 2025 at 02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'June 08, 2025 at 02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'June 08, 2025 AD at 02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): 'June 08, 2025 at 02:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.auto):
        'June 8, 2025 at 2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.full):
        'June 8, 2025 at 2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.withEra):
        'June 8, 2025 AD at 2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.long, null, null):
        'June 8, 2025 at 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'Jun 8, 2025, 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'Jun 8, 2025, 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'Jun 8, 2025 AD, 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): 'Jun 8, 2025, 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'Jun 08, 2025, 02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'Jun 08, 2025, 02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'Jun 08, 2025 AD, 02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): 'Jun 08, 2025, 02:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.auto):
        'Jun 8, 2025, 2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.full):
        'Jun 8, 2025, 2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.withEra):
        'Jun 8, 2025 AD, 2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, null):
        'Jun 8, 2025, 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '6/8/25, 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '6/8/2025, 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '6/8/2025 AD, 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '6/8/25, 2:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '06/08/25, 02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '06/08/2025, 02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '06/08/2025 AD, 02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '06/08/25, 02:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.auto):
        '6/8/25, 2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.full):
        '6/8/2025, 2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45.1 PM',
    (TimePrecision.subsecond1, DateTimeLength.short, null, null):
        '6/8/25, 2:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.auto):
        '6/8/25, 2:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.full):
        '6/8/2025, 2:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, null):
        '6/8/25, 2:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.column, YearStyle.auto):
        '06/08/25, 02:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.column, YearStyle.full):
        '06/08/2025, 02:30:45.1 PM',
    (
      TimePrecision.subsecond1,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '06/08/2025 AD, 02:30:45.1 PM',
    (TimePrecision.subsecond1, null, DateTimeAlignment.column, null):
        '06/08/25, 02:30:45.1 PM',
    (TimePrecision.subsecond1, null, null, YearStyle.auto):
        '6/8/25, 2:30:45.1 PM',
    (TimePrecision.subsecond1, null, null, YearStyle.full):
        '6/8/2025, 2:30:45.1 PM',
    (TimePrecision.subsecond1, null, null, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45.1 PM',
    (TimePrecision.subsecond1, null, null, null): '6/8/25, 2:30:45.1 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'June 8, 2025 at 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'June 8, 2025 at 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'June 8, 2025 AD at 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): 'June 8, 2025 at 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'June 08, 2025 at 02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'June 08, 2025 at 02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'June 08, 2025 AD at 02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): 'June 08, 2025 at 02:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.auto):
        'June 8, 2025 at 2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.full):
        'June 8, 2025 at 2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.withEra):
        'June 8, 2025 AD at 2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.long, null, null):
        'June 8, 2025 at 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'Jun 8, 2025, 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'Jun 8, 2025, 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'Jun 8, 2025 AD, 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): 'Jun 8, 2025, 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'Jun 08, 2025, 02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'Jun 08, 2025, 02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'Jun 08, 2025 AD, 02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): 'Jun 08, 2025, 02:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.auto):
        'Jun 8, 2025, 2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.full):
        'Jun 8, 2025, 2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.withEra):
        'Jun 8, 2025 AD, 2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, null):
        'Jun 8, 2025, 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '6/8/25, 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '6/8/2025, 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '6/8/2025 AD, 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '6/8/25, 2:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '06/08/25, 02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '06/08/2025, 02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '06/08/2025 AD, 02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '06/08/25, 02:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.auto):
        '6/8/25, 2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.full):
        '6/8/2025, 2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45.12 PM',
    (TimePrecision.subsecond2, DateTimeLength.short, null, null):
        '6/8/25, 2:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.auto):
        '6/8/25, 2:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.full):
        '6/8/2025, 2:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, null):
        '6/8/25, 2:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.column, YearStyle.auto):
        '06/08/25, 02:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.column, YearStyle.full):
        '06/08/2025, 02:30:45.12 PM',
    (
      TimePrecision.subsecond2,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '06/08/2025 AD, 02:30:45.12 PM',
    (TimePrecision.subsecond2, null, DateTimeAlignment.column, null):
        '06/08/25, 02:30:45.12 PM',
    (TimePrecision.subsecond2, null, null, YearStyle.auto):
        '6/8/25, 2:30:45.12 PM',
    (TimePrecision.subsecond2, null, null, YearStyle.full):
        '6/8/2025, 2:30:45.12 PM',
    (TimePrecision.subsecond2, null, null, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45.12 PM',
    (TimePrecision.subsecond2, null, null, null): '6/8/25, 2:30:45.12 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'June 8, 2025 at 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'June 8, 2025 at 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'June 8, 2025 AD at 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): 'June 8, 2025 at 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'June 08, 2025 at 02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'June 08, 2025 at 02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'June 08, 2025 AD at 02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): 'June 08, 2025 at 02:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.auto):
        'June 8, 2025 at 2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.full):
        'June 8, 2025 at 2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.withEra):
        'June 8, 2025 AD at 2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.long, null, null):
        'June 8, 2025 at 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): 'Jun 8, 2025, 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): 'Jun 8, 2025, 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): 'Jun 8, 2025 AD, 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): 'Jun 8, 2025, 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): 'Jun 08, 2025, 02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): 'Jun 08, 2025, 02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): 'Jun 08, 2025 AD, 02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): 'Jun 08, 2025, 02:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.auto):
        'Jun 8, 2025, 2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.full):
        'Jun 8, 2025, 2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.withEra):
        'Jun 8, 2025 AD, 2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, null):
        'Jun 8, 2025, 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '6/8/25, 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '6/8/2025, 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '6/8/2025 AD, 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '6/8/25, 2:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '06/08/25, 02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '06/08/2025, 02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '06/08/2025 AD, 02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '06/08/25, 02:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.auto):
        '6/8/25, 2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.full):
        '6/8/2025, 2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45.123 PM',
    (TimePrecision.subsecond3, DateTimeLength.short, null, null):
        '6/8/25, 2:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.auto):
        '6/8/25, 2:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.full):
        '6/8/2025, 2:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, null):
        '6/8/25, 2:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.column, YearStyle.auto):
        '06/08/25, 02:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.column, YearStyle.full):
        '06/08/2025, 02:30:45.123 PM',
    (
      TimePrecision.subsecond3,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '06/08/2025 AD, 02:30:45.123 PM',
    (TimePrecision.subsecond3, null, DateTimeAlignment.column, null):
        '06/08/25, 02:30:45.123 PM',
    (TimePrecision.subsecond3, null, null, YearStyle.auto):
        '6/8/25, 2:30:45.123 PM',
    (TimePrecision.subsecond3, null, null, YearStyle.full):
        '6/8/2025, 2:30:45.123 PM',
    (TimePrecision.subsecond3, null, null, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45.123 PM',
    (TimePrecision.subsecond3, null, null, null): '6/8/25, 2:30:45.123 PM',
    (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.auto):
        'June 8, 2025 at 2:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.full):
        'June 8, 2025 at 2:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.withEra):
        'June 8, 2025 AD at 2:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.auto, null):
        'June 8, 2025 at 2:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.auto):
        'June 08, 2025 at 02:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.full):
        'June 08, 2025 at 02:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.withEra):
        'June 08, 2025 AD at 02:30:45 PM',
    (null, DateTimeLength.long, DateTimeAlignment.column, null):
        'June 08, 2025 at 02:30:45 PM',
    (null, DateTimeLength.long, null, YearStyle.auto):
        'June 8, 2025 at 2:30:45 PM',
    (null, DateTimeLength.long, null, YearStyle.full):
        'June 8, 2025 at 2:30:45 PM',
    (null, DateTimeLength.long, null, YearStyle.withEra):
        'June 8, 2025 AD at 2:30:45 PM',
    (null, DateTimeLength.long, null, null): 'June 8, 2025 at 2:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.auto):
        'Jun 8, 2025, 2:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.full):
        'Jun 8, 2025, 2:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.withEra):
        'Jun 8, 2025 AD, 2:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, null):
        'Jun 8, 2025, 2:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.auto):
        'Jun 08, 2025, 02:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.full):
        'Jun 08, 2025, 02:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.withEra):
        'Jun 08, 2025 AD, 02:30:45 PM',
    (null, DateTimeLength.medium, DateTimeAlignment.column, null):
        'Jun 08, 2025, 02:30:45 PM',
    (null, DateTimeLength.medium, null, YearStyle.auto):
        'Jun 8, 2025, 2:30:45 PM',
    (null, DateTimeLength.medium, null, YearStyle.full):
        'Jun 8, 2025, 2:30:45 PM',
    (null, DateTimeLength.medium, null, YearStyle.withEra):
        'Jun 8, 2025 AD, 2:30:45 PM',
    (null, DateTimeLength.medium, null, null): 'Jun 8, 2025, 2:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.auto):
        '6/8/25, 2:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.full):
        '6/8/2025, 2:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.auto, null):
        '6/8/25, 2:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.auto):
        '06/08/25, 02:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.full):
        '06/08/2025, 02:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.withEra):
        '06/08/2025 AD, 02:30:45 PM',
    (null, DateTimeLength.short, DateTimeAlignment.column, null):
        '06/08/25, 02:30:45 PM',
    (null, DateTimeLength.short, null, YearStyle.auto): '6/8/25, 2:30:45 PM',
    (null, DateTimeLength.short, null, YearStyle.full): '6/8/2025, 2:30:45 PM',
    (null, DateTimeLength.short, null, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45 PM',
    (null, DateTimeLength.short, null, null): '6/8/25, 2:30:45 PM',
    (null, null, DateTimeAlignment.auto, YearStyle.auto): '6/8/25, 2:30:45 PM',
    (null, null, DateTimeAlignment.auto, YearStyle.full):
        '6/8/2025, 2:30:45 PM',
    (null, null, DateTimeAlignment.auto, YearStyle.withEra):
        '6/8/2025 AD, 2:30:45 PM',
    (null, null, DateTimeAlignment.auto, null): '6/8/25, 2:30:45 PM',
    (null, null, DateTimeAlignment.column, YearStyle.auto):
        '06/08/25, 02:30:45 PM',
    (null, null, DateTimeAlignment.column, YearStyle.full):
        '06/08/2025, 02:30:45 PM',
    (null, null, DateTimeAlignment.column, YearStyle.withEra):
        '06/08/2025 AD, 02:30:45 PM',
    (null, null, DateTimeAlignment.column, null): '06/08/25, 02:30:45 PM',
    (null, null, null, YearStyle.auto): '6/8/25, 2:30:45 PM',
    (null, null, null, YearStyle.full): '6/8/2025, 2:30:45 PM',
    (null, null, null, YearStyle.withEra): '6/8/2025 AD, 2:30:45 PM',
    (null, null, null, null): '6/8/25, 2:30:45 PM',
  },
  'de-DE': {
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '8. Juni 2025 um 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '8. Juni 2025 um 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '8. Juni 2025 n. Chr. um 14 Uhr',
    (TimePrecision.hour, DateTimeLength.long, DateTimeAlignment.auto, null):
        '8. Juni 2025 um 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08. Juni 2025 um 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08. Juni 2025 um 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08. Juni 2025 n. Chr. um 14 Uhr',
    (TimePrecision.hour, DateTimeLength.long, DateTimeAlignment.column, null):
        '08. Juni 2025 um 14 Uhr',
    (TimePrecision.hour, DateTimeLength.long, null, YearStyle.auto):
        '8. Juni 2025 um 14 Uhr',
    (TimePrecision.hour, DateTimeLength.long, null, YearStyle.full):
        '8. Juni 2025 um 14 Uhr',
    (TimePrecision.hour, DateTimeLength.long, null, YearStyle.withEra):
        '8. Juni 2025 n. Chr. um 14 Uhr',
    (TimePrecision.hour, DateTimeLength.long, null, null):
        '8. Juni 2025 um 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.2025, 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14 Uhr',
    (TimePrecision.hour, DateTimeLength.medium, DateTimeAlignment.auto, null):
        '08.06.2025, 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.2025, 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14 Uhr',
    (TimePrecision.hour, DateTimeLength.medium, DateTimeAlignment.column, null):
        '08.06.2025, 14 Uhr',
    (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.auto):
        '08.06.2025, 14 Uhr',
    (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.full):
        '08.06.2025, 14 Uhr',
    (TimePrecision.hour, DateTimeLength.medium, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14 Uhr',
    (TimePrecision.hour, DateTimeLength.medium, null, null):
        '08.06.2025, 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.25, 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14 Uhr',
    (TimePrecision.hour, DateTimeLength.short, DateTimeAlignment.auto, null):
        '08.06.25, 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.25, 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14 Uhr',
    (
      TimePrecision.hour,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14 Uhr',
    (TimePrecision.hour, DateTimeLength.short, DateTimeAlignment.column, null):
        '08.06.25, 14 Uhr',
    (TimePrecision.hour, DateTimeLength.short, null, YearStyle.auto):
        '08.06.25, 14 Uhr',
    (TimePrecision.hour, DateTimeLength.short, null, YearStyle.full):
        '08.06.2025, 14 Uhr',
    (TimePrecision.hour, DateTimeLength.short, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14 Uhr',
    (TimePrecision.hour, DateTimeLength.short, null, null): '08.06.25, 14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.auto):
        '08.06.25, 14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.full):
        '08.06.2025, 14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.auto, YearStyle.withEra):
        '08.06.2025 n. Chr., 14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.auto, null):
        '08.06.25, 14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.auto):
        '08.06.25, 14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.full):
        '08.06.2025, 14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.column, YearStyle.withEra):
        '08.06.2025 n. Chr., 14 Uhr',
    (TimePrecision.hour, null, DateTimeAlignment.column, null):
        '08.06.25, 14 Uhr',
    (TimePrecision.hour, null, null, YearStyle.auto): '08.06.25, 14 Uhr',
    (TimePrecision.hour, null, null, YearStyle.full): '08.06.2025, 14 Uhr',
    (TimePrecision.hour, null, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14 Uhr',
    (TimePrecision.hour, null, null, null): '08.06.25, 14 Uhr',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '8. Juni 2025 um 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '8. Juni 2025 um 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '8. Juni 2025 n. Chr. um 14:30',
    (TimePrecision.minute, DateTimeLength.long, DateTimeAlignment.auto, null):
        '8. Juni 2025 um 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08. Juni 2025 um 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08. Juni 2025 um 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08. Juni 2025 n. Chr. um 14:30',
    (TimePrecision.minute, DateTimeLength.long, DateTimeAlignment.column, null):
        '08. Juni 2025 um 14:30',
    (TimePrecision.minute, DateTimeLength.long, null, YearStyle.auto):
        '8. Juni 2025 um 14:30',
    (TimePrecision.minute, DateTimeLength.long, null, YearStyle.full):
        '8. Juni 2025 um 14:30',
    (TimePrecision.minute, DateTimeLength.long, null, YearStyle.withEra):
        '8. Juni 2025 n. Chr. um 14:30',
    (TimePrecision.minute, DateTimeLength.long, null, null):
        '8. Juni 2025 um 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30',
    (TimePrecision.minute, DateTimeLength.medium, DateTimeAlignment.auto, null):
        '08.06.2025, 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '08.06.2025, 14:30',
    (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.auto):
        '08.06.2025, 14:30',
    (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.full):
        '08.06.2025, 14:30',
    (TimePrecision.minute, DateTimeLength.medium, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30',
    (TimePrecision.minute, DateTimeLength.medium, null, null):
        '08.06.2025, 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.25, 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30',
    (TimePrecision.minute, DateTimeLength.short, DateTimeAlignment.auto, null):
        '08.06.25, 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.25, 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30',
    (
      TimePrecision.minute,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '08.06.25, 14:30',
    (TimePrecision.minute, DateTimeLength.short, null, YearStyle.auto):
        '08.06.25, 14:30',
    (TimePrecision.minute, DateTimeLength.short, null, YearStyle.full):
        '08.06.2025, 14:30',
    (TimePrecision.minute, DateTimeLength.short, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30',
    (TimePrecision.minute, DateTimeLength.short, null, null): '08.06.25, 14:30',
    (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.auto):
        '08.06.25, 14:30',
    (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.full):
        '08.06.2025, 14:30',
    (TimePrecision.minute, null, DateTimeAlignment.auto, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30',
    (TimePrecision.minute, null, DateTimeAlignment.auto, null):
        '08.06.25, 14:30',
    (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.auto):
        '08.06.25, 14:30',
    (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.full):
        '08.06.2025, 14:30',
    (TimePrecision.minute, null, DateTimeAlignment.column, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30',
    (TimePrecision.minute, null, DateTimeAlignment.column, null):
        '08.06.25, 14:30',
    (TimePrecision.minute, null, null, YearStyle.auto): '08.06.25, 14:30',
    (TimePrecision.minute, null, null, YearStyle.full): '08.06.2025, 14:30',
    (TimePrecision.minute, null, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30',
    (TimePrecision.minute, null, null, null): '08.06.25, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '8. Juni 2025 um 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '8. Juni 2025 um 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '8. Juni 2025 n. Chr. um 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): '8. Juni 2025 um 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08. Juni 2025 um 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08. Juni 2025 um 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08. Juni 2025 n. Chr. um 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): '08. Juni 2025 um 14:30',
    (TimePrecision.minuteOptional, DateTimeLength.long, null, YearStyle.auto):
        '8. Juni 2025 um 14:30',
    (TimePrecision.minuteOptional, DateTimeLength.long, null, YearStyle.full):
        '8. Juni 2025 um 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.long,
      null,
      YearStyle.withEra,
    ): '8. Juni 2025 n. Chr. um 14:30',
    (TimePrecision.minuteOptional, DateTimeLength.long, null, null):
        '8. Juni 2025 um 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '08.06.2025, 14:30',
    (TimePrecision.minuteOptional, DateTimeLength.medium, null, YearStyle.auto):
        '08.06.2025, 14:30',
    (TimePrecision.minuteOptional, DateTimeLength.medium, null, YearStyle.full):
        '08.06.2025, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.medium,
      null,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30',
    (TimePrecision.minuteOptional, DateTimeLength.medium, null, null):
        '08.06.2025, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.25, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '08.06.25, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.25, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '08.06.25, 14:30',
    (TimePrecision.minuteOptional, DateTimeLength.short, null, YearStyle.auto):
        '08.06.25, 14:30',
    (TimePrecision.minuteOptional, DateTimeLength.short, null, YearStyle.full):
        '08.06.2025, 14:30',
    (
      TimePrecision.minuteOptional,
      DateTimeLength.short,
      null,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30',
    (TimePrecision.minuteOptional, DateTimeLength.short, null, null):
        '08.06.25, 14:30',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.25, 14:30',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30',
    (TimePrecision.minuteOptional, null, DateTimeAlignment.auto, null):
        '08.06.25, 14:30',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.25, 14:30',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30',
    (
      TimePrecision.minuteOptional,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30',
    (TimePrecision.minuteOptional, null, DateTimeAlignment.column, null):
        '08.06.25, 14:30',
    (TimePrecision.minuteOptional, null, null, YearStyle.auto):
        '08.06.25, 14:30',
    (TimePrecision.minuteOptional, null, null, YearStyle.full):
        '08.06.2025, 14:30',
    (TimePrecision.minuteOptional, null, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30',
    (TimePrecision.minuteOptional, null, null, null): '08.06.25, 14:30',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '8. Juni 2025 um 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '8. Juni 2025 um 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '8. Juni 2025 n. Chr. um 14:30:45',
    (TimePrecision.second, DateTimeLength.long, DateTimeAlignment.auto, null):
        '8. Juni 2025 um 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08. Juni 2025 um 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08. Juni 2025 um 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08. Juni 2025 n. Chr. um 14:30:45',
    (TimePrecision.second, DateTimeLength.long, DateTimeAlignment.column, null):
        '08. Juni 2025 um 14:30:45',
    (TimePrecision.second, DateTimeLength.long, null, YearStyle.auto):
        '8. Juni 2025 um 14:30:45',
    (TimePrecision.second, DateTimeLength.long, null, YearStyle.full):
        '8. Juni 2025 um 14:30:45',
    (TimePrecision.second, DateTimeLength.long, null, YearStyle.withEra):
        '8. Juni 2025 n. Chr. um 14:30:45',
    (TimePrecision.second, DateTimeLength.long, null, null):
        '8. Juni 2025 um 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.2025, 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45',
    (TimePrecision.second, DateTimeLength.medium, DateTimeAlignment.auto, null):
        '08.06.2025, 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.2025, 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '08.06.2025, 14:30:45',
    (TimePrecision.second, DateTimeLength.medium, null, YearStyle.auto):
        '08.06.2025, 14:30:45',
    (TimePrecision.second, DateTimeLength.medium, null, YearStyle.full):
        '08.06.2025, 14:30:45',
    (TimePrecision.second, DateTimeLength.medium, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (TimePrecision.second, DateTimeLength.medium, null, null):
        '08.06.2025, 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.25, 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45',
    (TimePrecision.second, DateTimeLength.short, DateTimeAlignment.auto, null):
        '08.06.25, 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.25, 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45',
    (
      TimePrecision.second,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '08.06.25, 14:30:45',
    (TimePrecision.second, DateTimeLength.short, null, YearStyle.auto):
        '08.06.25, 14:30:45',
    (TimePrecision.second, DateTimeLength.short, null, YearStyle.full):
        '08.06.2025, 14:30:45',
    (TimePrecision.second, DateTimeLength.short, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (TimePrecision.second, DateTimeLength.short, null, null):
        '08.06.25, 14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.auto):
        '08.06.25, 14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.full):
        '08.06.2025, 14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.auto, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.auto, null):
        '08.06.25, 14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.auto):
        '08.06.25, 14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.full):
        '08.06.2025, 14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.column, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (TimePrecision.second, null, DateTimeAlignment.column, null):
        '08.06.25, 14:30:45',
    (TimePrecision.second, null, null, YearStyle.auto): '08.06.25, 14:30:45',
    (TimePrecision.second, null, null, YearStyle.full): '08.06.2025, 14:30:45',
    (TimePrecision.second, null, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (TimePrecision.second, null, null, null): '08.06.25, 14:30:45',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '8. Juni 2025 um 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '8. Juni 2025 um 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '8. Juni 2025 n. Chr. um 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): '8. Juni 2025 um 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08. Juni 2025 um 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08. Juni 2025 um 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08. Juni 2025 n. Chr. um 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): '08. Juni 2025 um 14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.auto):
        '8. Juni 2025 um 14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.full):
        '8. Juni 2025 um 14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.long, null, YearStyle.withEra):
        '8. Juni 2025 n. Chr. um 14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.long, null, null):
        '8. Juni 2025 um 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.2025, 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): '08.06.2025, 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.2025, 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '08.06.2025, 14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.auto):
        '08.06.2025, 14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.full):
        '08.06.2025, 14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.medium, null, null):
        '08.06.2025, 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.25, 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '08.06.25, 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.25, 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,1',
    (
      TimePrecision.subsecond1,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '08.06.25, 14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.auto):
        '08.06.25, 14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.full):
        '08.06.2025, 14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.short, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45,1',
    (TimePrecision.subsecond1, DateTimeLength.short, null, null):
        '08.06.25, 14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.auto):
        '08.06.25, 14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.full):
        '08.06.2025, 14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.auto, null):
        '08.06.25, 14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.column, YearStyle.auto):
        '08.06.25, 14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.column, YearStyle.full):
        '08.06.2025, 14:30:45,1',
    (
      TimePrecision.subsecond1,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,1',
    (TimePrecision.subsecond1, null, DateTimeAlignment.column, null):
        '08.06.25, 14:30:45,1',
    (TimePrecision.subsecond1, null, null, YearStyle.auto):
        '08.06.25, 14:30:45,1',
    (TimePrecision.subsecond1, null, null, YearStyle.full):
        '08.06.2025, 14:30:45,1',
    (TimePrecision.subsecond1, null, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45,1',
    (TimePrecision.subsecond1, null, null, null): '08.06.25, 14:30:45,1',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '8. Juni 2025 um 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '8. Juni 2025 um 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '8. Juni 2025 n. Chr. um 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): '8. Juni 2025 um 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08. Juni 2025 um 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08. Juni 2025 um 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08. Juni 2025 n. Chr. um 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): '08. Juni 2025 um 14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.auto):
        '8. Juni 2025 um 14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.full):
        '8. Juni 2025 um 14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.long, null, YearStyle.withEra):
        '8. Juni 2025 n. Chr. um 14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.long, null, null):
        '8. Juni 2025 um 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.2025, 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): '08.06.2025, 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.2025, 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '08.06.2025, 14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.auto):
        '08.06.2025, 14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.full):
        '08.06.2025, 14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.medium, null, null):
        '08.06.2025, 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.25, 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '08.06.25, 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.25, 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,12',
    (
      TimePrecision.subsecond2,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '08.06.25, 14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.auto):
        '08.06.25, 14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.full):
        '08.06.2025, 14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.short, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45,12',
    (TimePrecision.subsecond2, DateTimeLength.short, null, null):
        '08.06.25, 14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.auto):
        '08.06.25, 14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.full):
        '08.06.2025, 14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.auto, null):
        '08.06.25, 14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.column, YearStyle.auto):
        '08.06.25, 14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.column, YearStyle.full):
        '08.06.2025, 14:30:45,12',
    (
      TimePrecision.subsecond2,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,12',
    (TimePrecision.subsecond2, null, DateTimeAlignment.column, null):
        '08.06.25, 14:30:45,12',
    (TimePrecision.subsecond2, null, null, YearStyle.auto):
        '08.06.25, 14:30:45,12',
    (TimePrecision.subsecond2, null, null, YearStyle.full):
        '08.06.2025, 14:30:45,12',
    (TimePrecision.subsecond2, null, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45,12',
    (TimePrecision.subsecond2, null, null, null): '08.06.25, 14:30:45,12',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '8. Juni 2025 um 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '8. Juni 2025 um 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '8. Juni 2025 n. Chr. um 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.auto,
      null,
    ): '8. Juni 2025 um 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08. Juni 2025 um 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08. Juni 2025 um 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08. Juni 2025 n. Chr. um 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.long,
      DateTimeAlignment.column,
      null,
    ): '08. Juni 2025 um 14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.auto):
        '8. Juni 2025 um 14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.full):
        '8. Juni 2025 um 14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.long, null, YearStyle.withEra):
        '8. Juni 2025 n. Chr. um 14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.long, null, null):
        '8. Juni 2025 um 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.2025, 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.auto,
      null,
    ): '08.06.2025, 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.2025, 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.medium,
      DateTimeAlignment.column,
      null,
    ): '08.06.2025, 14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.auto):
        '08.06.2025, 14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.full):
        '08.06.2025, 14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.medium, null, null):
        '08.06.2025, 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.auto,
    ): '08.06.25, 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.full,
    ): '08.06.2025, 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.auto,
      null,
    ): '08.06.25, 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.auto,
    ): '08.06.25, 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.full,
    ): '08.06.2025, 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,123',
    (
      TimePrecision.subsecond3,
      DateTimeLength.short,
      DateTimeAlignment.column,
      null,
    ): '08.06.25, 14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.auto):
        '08.06.25, 14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.full):
        '08.06.2025, 14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.short, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45,123',
    (TimePrecision.subsecond3, DateTimeLength.short, null, null):
        '08.06.25, 14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.auto):
        '08.06.25, 14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.full):
        '08.06.2025, 14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.auto, null):
        '08.06.25, 14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.column, YearStyle.auto):
        '08.06.25, 14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.column, YearStyle.full):
        '08.06.2025, 14:30:45,123',
    (
      TimePrecision.subsecond3,
      null,
      DateTimeAlignment.column,
      YearStyle.withEra,
    ): '08.06.2025 n. Chr., 14:30:45,123',
    (TimePrecision.subsecond3, null, DateTimeAlignment.column, null):
        '08.06.25, 14:30:45,123',
    (TimePrecision.subsecond3, null, null, YearStyle.auto):
        '08.06.25, 14:30:45,123',
    (TimePrecision.subsecond3, null, null, YearStyle.full):
        '08.06.2025, 14:30:45,123',
    (TimePrecision.subsecond3, null, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45,123',
    (TimePrecision.subsecond3, null, null, null): '08.06.25, 14:30:45,123',
    (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.auto):
        '8. Juni 2025 um 14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.full):
        '8. Juni 2025 um 14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.auto, YearStyle.withEra):
        '8. Juni 2025 n. Chr. um 14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.auto, null):
        '8. Juni 2025 um 14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.auto):
        '08. Juni 2025 um 14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.full):
        '08. Juni 2025 um 14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.column, YearStyle.withEra):
        '08. Juni 2025 n. Chr. um 14:30:45',
    (null, DateTimeLength.long, DateTimeAlignment.column, null):
        '08. Juni 2025 um 14:30:45',
    (null, DateTimeLength.long, null, YearStyle.auto):
        '8. Juni 2025 um 14:30:45',
    (null, DateTimeLength.long, null, YearStyle.full):
        '8. Juni 2025 um 14:30:45',
    (null, DateTimeLength.long, null, YearStyle.withEra):
        '8. Juni 2025 n. Chr. um 14:30:45',
    (null, DateTimeLength.long, null, null): '8. Juni 2025 um 14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.auto):
        '08.06.2025, 14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.full):
        '08.06.2025, 14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.auto, null):
        '08.06.2025, 14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.auto):
        '08.06.2025, 14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.full):
        '08.06.2025, 14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.column, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (null, DateTimeLength.medium, DateTimeAlignment.column, null):
        '08.06.2025, 14:30:45',
    (null, DateTimeLength.medium, null, YearStyle.auto): '08.06.2025, 14:30:45',
    (null, DateTimeLength.medium, null, YearStyle.full): '08.06.2025, 14:30:45',
    (null, DateTimeLength.medium, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (null, DateTimeLength.medium, null, null): '08.06.2025, 14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.auto):
        '08.06.25, 14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.full):
        '08.06.2025, 14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.auto, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.auto, null):
        '08.06.25, 14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.auto):
        '08.06.25, 14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.full):
        '08.06.2025, 14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.column, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (null, DateTimeLength.short, DateTimeAlignment.column, null):
        '08.06.25, 14:30:45',
    (null, DateTimeLength.short, null, YearStyle.auto): '08.06.25, 14:30:45',
    (null, DateTimeLength.short, null, YearStyle.full): '08.06.2025, 14:30:45',
    (null, DateTimeLength.short, null, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (null, DateTimeLength.short, null, null): '08.06.25, 14:30:45',
    (null, null, DateTimeAlignment.auto, YearStyle.auto): '08.06.25, 14:30:45',
    (null, null, DateTimeAlignment.auto, YearStyle.full):
        '08.06.2025, 14:30:45',
    (null, null, DateTimeAlignment.auto, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (null, null, DateTimeAlignment.auto, null): '08.06.25, 14:30:45',
    (null, null, DateTimeAlignment.column, YearStyle.auto):
        '08.06.25, 14:30:45',
    (null, null, DateTimeAlignment.column, YearStyle.full):
        '08.06.2025, 14:30:45',
    (null, null, DateTimeAlignment.column, YearStyle.withEra):
        '08.06.2025 n. Chr., 14:30:45',
    (null, null, DateTimeAlignment.column, null): '08.06.25, 14:30:45',
    (null, null, null, YearStyle.auto): '08.06.25, 14:30:45',
    (null, null, null, YearStyle.full): '08.06.2025, 14:30:45',
    (null, null, null, YearStyle.withEra): '08.06.2025 n. Chr., 14:30:45',
    (null, null, null, null): '08.06.25, 14:30:45',
  },
};
