name: messages_shrinker
description: Removing unneeded messages from message data files for package:messages.
version: 0.2.2-wip
repository: https://github.com/dart-lang/i18n/pkgs/messages_shrinker
issue_tracker: https://github.com/dart-lang/i18n/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Amessages_shrinker

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  analyzer: ^6.2.0
  args: ^2.4.2
  messages: ^0.2.0
  messages_builder: ^0.2.0
  messages_serializer: ^0.2.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  intl: ^0.19.0
  test: ^1.21.0
