// Copyright (c) 2024, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:io';

import 'package:messages_builder/builder.dart';
import 'package:messages_builder/generation_options.dart';
import 'package:path/path.dart' as path;
import 'package:test/test.dart';

void main() {
  group('deleteOldGeneratedFiles', () {
    late Directory tempDir;
    late Directory codeDir;
    late Directory assetsDir;

    setUp(() async {
      tempDir = await Directory.systemTemp.createTemp('messages_delete_test_');
      codeDir = Directory(path.join(tempDir.path, 'lib', 'src'))
        ..createSync(recursive: true);
      assetsDir = Directory(path.join(tempDir.path, 'assets'))
        ..createSync(recursive: true);
    });

    tearDown(() async {
      await tempDir.delete(recursive: true);
    });

    test('deletes old generated .g.dart and .arb.json files', () async {
      // 1. Generated dart file
      final oldGenDart = File(path.join(codeDir.path, 'old_messages.g.dart'));
      await oldGenDart.writeAsString(
        '// Generated by package:messages_builder.\nclass Old {}',
      );

      // 2. Generated helper dart file
      final oldHelperDart = File(path.join(codeDir.path, 'old_en_data.g.dart'));
      await oldHelperDart.writeAsString(
        '// Generated by package:messages_builder.\nconst String data = "";',
      );

      // 3. Generated asset file
      final oldAsset = File(path.join(assetsDir.path, 'old_en.arb.json'));
      await oldAsset.writeAsString('[0,"en"]');

      // 4. Non-generated user dart file (should NOT be deleted)
      final userDart = File(path.join(codeDir.path, 'user_code.g.dart'));
      await userDart.writeAsString(
        '// Generated by json_serializable\nclass User {}',
      );

      // 5. Non-generated asset file (should NOT be deleted)
      final userFile = File(path.join(assetsDir.path, 'config.json'));
      await userFile.writeAsString('{"key": "value"}');

      final options = GenerationOptions(
        serialization: SerializationType.json,
        deserialization: DeserializationType.web,
        header: 'Generated by package:messages_builder.',
        pluralSelector: PluralSelectorType.intl,
        assetLoadingStyle: AssetLoadingStyle.flutter,
        packageName: 'test_pkg',
        arbFolder: Directory(path.join(tempDir.path, 'assets', 'l10n')),
        messageFolder: assetsDir,
        codeOutputFolder: codeDir,
      );

      await deleteOldGeneratedFiles(options);

      expect(oldGenDart.existsSync(), isFalse);
      expect(oldHelperDart.existsSync(), isFalse);
      expect(oldAsset.existsSync(), isFalse);

      expect(userDart.existsSync(), isTrue);
      expect(userFile.existsSync(), isTrue);
    });
  });
}
