// Copyright (c) 2023, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:messages_builder/generation_options.dart';
import 'package:test/test.dart';

void main() {
  group('GenerationOptions.fromPubspec', () {
    test('parses default options correctly', () async {
      const pubspec = '''
name: my_package
''';
      final options = await GenerationOptions.fromPubspec(pubspec);
      expect(options.packageName, 'my_package');
      expect(options.pluralSelector, PluralSelectorType.intl);
      expect(options.header, 'Generated by package:messages_builder.');
      expect(options.arbFolder.path, 'assets/l10n/');
      expect(options.messageFolder.path, 'assets/');
      expect(options.codeOutputFolder.path, 'lib/src/');
    });

    test('parses custom options correctly', () async {
      const pubspec = '''
name: custom_package
package_options:
  messages_builder:
    plural_selector: intl4x
    header: "// Custom Header"
    arb_input_folder: l10n/
    message_output_folder: out_assets/
    code_output_folder: lib/generated/
''';
      final options = await GenerationOptions.fromPubspec(pubspec);
      expect(options.packageName, 'custom_package');
      expect(options.pluralSelector, PluralSelectorType.intl4x);
      expect(
        options.header,
        '// Custom Header\nGenerated by package:messages_builder.',
      );
      expect(options.arbFolder.path, 'l10n/');
      expect(options.messageFolder.path, 'out_assets/');
      expect(options.codeOutputFolder.path, 'lib/generated/');
    });

    test('parses plural_selector: custom correctly', () async {
      const pubspec = '''
name: custom_plural_package
package_options:
  messages_builder:
    plural_selector: custom
''';
      final options = await GenerationOptions.fromPubspec(pubspec);
      expect(options.pluralSelector, PluralSelectorType.custom);
    });

    test('parses asset_loading_style option correctly', () async {
      const flutterPubspec = '''
name: flutter_pkg
package_options:
  messages_builder:
    asset_loading_style: flutter
''';
      final flutterOptions = await GenerationOptions.fromPubspec(
        flutterPubspec,
      );
      expect(flutterOptions.assetLoadingStyle, AssetLoadingStyle.flutter);

      const dartPubspec = '''
name: dart_pkg
package_options:
  messages_builder:
    asset_loading_style: dart
''';
      final dartOptions = await GenerationOptions.fromPubspec(dartPubspec);
      expect(dartOptions.assetLoadingStyle, AssetLoadingStyle.dart);

      const manualPubspec = '''
name: manual_pkg
package_options:
  messages_builder:
    asset_loading_style: manual
''';
      final manualOptions = await GenerationOptions.fromPubspec(manualPubspec);
      expect(manualOptions.assetLoadingStyle, AssetLoadingStyle.manual);
    });

    test('throws ArgumentError on invalid asset_loading_style value', () async {
      const invalidTargetPubspec = '''
name: invalid_target_pkg
package_options:
  messages_builder:
    asset_loading_style: invalid_value
''';
      expect(
        () => GenerationOptions.fromPubspec(invalidTargetPubspec),
        throwsA(isA<ArgumentError>()),
      );
    });

    test('auto-detects flutter dependency', () async {
      const flutterPubspec = '''
name: auto_flutter
dependencies:
  flutter:
    sdk: flutter
''';
      final options = await GenerationOptions.fromPubspec(flutterPubspec);
      expect(options.assetLoadingStyle, AssetLoadingStyle.flutter);
    });

    test('throws ArgumentError on illegal key', () async {
      const pubspec = '''
name: invalid_package
package_options:
  messages_builder:
    unknown_invalid_key: true
''';
      expect(
        () => GenerationOptions.fromPubspec(pubspec),
        throwsA(isA<ArgumentError>()),
      );
    });
  });
}
