name: messages_example
description: An example on how to use `package:messages`.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  intl4x:
    path: ../../intl4x
  messages: ^0.3.0-wip

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
  lints: ^6.0.0
  messages_builder: any
  path: ^1.8.3
  test: ^1.16.0

package_options:
  messages_builder:
    plural_selector: intl4x
    arb_input_folder: assets/l10n/
    message_output_folder: assets/
    code_output_folder: lib/
