name: my_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.0
  messages: ^0.3.0-wip
  my_shopping_cart: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  messages_builder: ^0.3.0-wip

flutter:
  uses-material-design: true

  deferred-components:
    - name: enMessages
      libraries:
        - package:my_application/src/my_app_en_US_empty.g.dart
      assets:
        - assets/messages.arb.json
    - name: deMessages
      libraries:
        - package:my_application/src/my_app_de_DE_empty.g.dart
      assets:
        - assets/messages_de.arb.json

