name: my_shopping_cart
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.6.0-78.0.dev

publish_to: none

dependencies:
  messages:
    path: ../../../messages

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
