// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:intl4x/datetime_format.dart';

void main() {
  final localeString = ['en-US', 'de-DE'];
  writeFor('ymdet', DateTimeFormat.yearMonthDayWeekdayTime, localeString);
  writeFor('ymdt', DateTimeFormat.yearMonthDayTime, localeString);
  writeFor(
    'mdt',
    ({locale, alignment, length, timePrecision, yearStyle}) =>
        DateTimeFormat.monthDayTime(
          locale: locale,
          alignment: alignment,
          length: length,
          timePrecision: timePrecision,
        ),
    localeString,
  );
  writeFor(
    'ymde',
    ({locale, alignment, length, timePrecision, yearStyle}) =>
        DateTimeFormat.yearMonthDayWeekday(
          locale: locale,
          alignment: alignment,
          length: length,
          yearStyle: yearStyle,
        ),
    localeString,
  );
  writeFor(
    'ymd',
    ({locale, alignment, length, timePrecision, yearStyle}) =>
        DateTimeFormat.yearMonthDay(
          locale: locale,
          alignment: alignment,
          length: length,
          yearStyle: yearStyle,
        ),
    localeString,
  );
  writeFor(
    'ymde',
    ({locale, alignment, length, timePrecision, yearStyle}) =>
        DateTimeFormat.yearMonthDayWeekday(
          locale: locale,
          alignment: alignment,
          length: length,
          yearStyle: yearStyle,
        ),
    localeString,
  );
  writeFor(
    'y',
    ({locale, alignment, length, timePrecision, yearStyle}) =>
        DateTimeFormat.year(
          locale: locale,
          alignment: alignment,
          length: length,
          yearStyle: yearStyle,
        ),
    localeString,
  );
  writeFor(
    't',
    ({locale, alignment, length, timePrecision, yearStyle}) =>
        DateTimeFormat.time(
          locale: locale,
          alignment: alignment,
          length: length,
          timePrecision: timePrecision,
        ),
    localeString,
  );
  writeFor(
    'md',
    ({locale, alignment, length, timePrecision, yearStyle}) =>
        DateTimeFormat.monthDay(
          locale: locale,
          alignment: alignment,
          length: length,
        ),
    localeString,
  );
  writeFor(
    'm',
    ({locale, alignment, length, timePrecision, yearStyle}) =>
        DateTimeFormat.month(
          locale: locale,
          alignment: alignment,
          length: length,
        ),
    localeString,
  );
  writeFor(
    'd',
    ({locale, alignment, length, timePrecision, yearStyle}) =>
        DateTimeFormat.day(
          locale: locale,
          alignment: alignment,
          length: length,
        ),
    localeString,
  );
}

void writeFor(
  String type,
  DateTimeFormatterStandalone Function({
    Locale? locale,
    DateTimeAlignment? alignment,
    DateTimeLength? length,
    TimePrecision? timePrecision,
    YearStyle? yearStyle,
  })
  formatter,
  List<String> localeString,
) {
  final code = StringBuffer();

  final precisionValues = [...TimePrecision.values, null];
  final lengthValues = [...DateTimeLength.values, null];
  final alignmentValues = [...DateTimeAlignment.values, null];
  final yearStyleValues = [...YearStyle.values, null];
  final dateTime = DateTime(2025, 6, 8, 14, 30, 45, 123);

  code.writeln('''
// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:intl4x/datetime_format.dart';

// Generated content: Do not edit this file manually.
// Regenerate by running `dart run test/tools/regenerate_conformance_data.dart`

final ${type}Options = {
''');

  for (final locale in localeString) {
    code.writeln("'$locale': {");

    for (final precision in precisionValues) {
      for (final length in lengthValues) {
        for (final alignment in alignmentValues) {
          for (final yearStyle in yearStyleValues) {
            final format = formatter(
              locale: Locale.parse(locale),
              length: length,
              timePrecision: precision,
              alignment: alignment,
              yearStyle: yearStyle,
            ).format(dateTime);

            String keyString;

            if (precision != null &&
                length != null &&
                alignment != null &&
                yearStyle != null) {
              keyString = '''
(\n    $precision,\n    $length,\n    $alignment,\n    $yearStyle,\n  )''';
            } else {
              keyString = '($precision, $length, $alignment, $yearStyle)';
            }

            code.writeln('$keyString: \'$format\',');
          }
        }
      }
    }
    code.writeln('},');
  }
  code.writeln('};');

  final formattedCode = DartFormatter(
    languageVersion: DartFormatter.latestLanguageVersion,
  ).format(code.toString());

  final path = 'test/datetime_format_conformance_data/$type.g.dart';
  final file = File(path);
  try {
    file.createSync();
    file.writeAsStringSync(formattedCode);
    print('Successfully generated map content and wrote to $path');
  } catch (e) {
    print('Error writing to file $path: $e');
  }
}
