// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:intl4x/datetime_format.dart';

void main() {
  final dateTimeFormat = DateTimeFormat(locale: Locale.parse('de-DE'));
  writeFor('ymdet', dateTimeFormat.ymdet);
  writeFor('ymdt', dateTimeFormat.ymdt);
  writeFor(
    'mdt',
    ({alignment, length, timePrecision, yearStyle}) => dateTimeFormat.mdt(
      alignment: alignment,
      length: length,
      timePrecision: timePrecision,
    ),
  );
  writeFor(
    'ymde',
    ({alignment, length, timePrecision, yearStyle}) => dateTimeFormat.ymde(
      alignment: alignment,
      length: length,
      yearStyle: yearStyle,
    ),
  );
  writeFor(
    'ymd',
    ({alignment, length, timePrecision, yearStyle}) => dateTimeFormat.ymd(
      alignment: alignment,
      length: length,
      yearStyle: yearStyle,
    ),
  );
  writeFor(
    'ymde',
    ({alignment, length, timePrecision, yearStyle}) => dateTimeFormat.ymde(
      alignment: alignment,
      length: length,
      yearStyle: yearStyle,
    ),
  );
  writeFor(
    'y',
    ({alignment, length, timePrecision, yearStyle}) => dateTimeFormat.y(
      alignment: alignment,
      length: length,
      yearStyle: yearStyle,
    ),
  );
  writeFor(
    't',
    ({alignment, length, timePrecision, yearStyle}) => dateTimeFormat.t(
      alignment: alignment,
      length: length,
      timePrecision: timePrecision,
    ),
  );
  writeFor(
    'md',
    ({alignment, length, timePrecision, yearStyle}) =>
        dateTimeFormat.md(alignment: alignment, length: length),
  );
  writeFor(
    'm',
    ({alignment, length, timePrecision, yearStyle}) =>
        dateTimeFormat.m(alignment: alignment, length: length),
  );
  writeFor(
    'd',
    ({alignment, length, timePrecision, yearStyle}) =>
        dateTimeFormat.d(alignment: alignment, length: length),
  );
}

void writeFor(
  String type,
  DateTimeFormatter Function({
    DateTimeAlignment? alignment,
    DateTimeLength? length,
    TimePrecision? timePrecision,
    YearStyle? yearStyle,
  })
  ymdet,
) {
  final code = StringBuffer();

  final precisionValues = [...TimePrecision.values, null];
  final lengthValues = [...DateTimeLength.values, null];
  final alignmentValues = [...DateTimeAlignment.values, null];
  final yearStyleValues = [...YearStyle.values, null];
  final dateTime = DateTime(2025, 6, 18, 10, 30, 45, 123);

  code.writeln('''
// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:intl4x/datetime_format.dart';

// Generated content: Do not edit this file manually.
// Regenerate by running `dart run test/tools/regenerate_conformance_data.dart`

final ${type}Options = {
''');

  for (final precision in precisionValues) {
    for (final length in lengthValues) {
      for (final alignment in alignmentValues) {
        for (final yearStyle in yearStyleValues) {
          // Generate the formatted string for the current combination
          final format = ymdet(
            length: length,
            timePrecision: precision,
            alignment: alignment,
            yearStyle: yearStyle,
          ).format(dateTime);

          String keyString;

          // Format the key to be multiline for non-null values for readability
          if (precision != null &&
              length != null &&
              alignment != null &&
              yearStyle != null) {
            keyString = '''
(\n    $precision,\n    $length,\n    $alignment,\n    $yearStyle,\n  )''';
          } else {
            // Keep null value combinations on a single line
            keyString = '($precision, $length, $alignment, $yearStyle)';
          }

          code.writeln('$keyString: \'$format\',');
        }
      }
    }
  }
  code.writeln('};');

  final formattedCode = DartFormatter(
    languageVersion: DartFormatter.latestLanguageVersion,
  ).format(code.toString());

  final path = 'test/datetime_format_conformance_data/$type.dart';
  final file = File(path);
  try {
    file.createSync();
    file.writeAsStringSync(formattedCode);
    print('Successfully generated map content and wrote to $path');
  } catch (e) {
    print('Error writing to file $path: $e');
  }
}
