name: Ecosystem test

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
        
jobs:
  test_ecosystem:
    uses: mosuem/ecosystem/.github/workflows/ecosystem_test.yaml@main
    with:
      repos_file: .github/test_repos/repos.json
