# A CI configuration to auto-publish pub packages.

name: Publish

on:
  pull_request:
    branches: [ main ]
  push:
    tags: [ '[0-9A-z]+-v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  publish:
    if: ${{ github.repository_owner == 'dart-lang' }}
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    with:
      sdk: dev
      write-comments: false
      checkout_submodules: true
      ignore-packages: "submodules"
