include: package:dart_flutter_team_lints/analysis_options.yaml

linter:
  rules:
    - conditional_uri_does_not_exist
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_relative_imports
    - unnecessary_parenthesis

analyzer:
  exclude:
    - "submodules/*"
    - "lib/src/bindings/*"
    - lib/src/hook_helpers/build_libs.g.dart
    - tool/build_libs.g.dart

  enable-experiment:
    - native-assets
