name: intl4x
description: >-
  A lightweight modular library for internationalization (i18n) functionality.
version: 1.0.1-alpha
repository: https://github.com/dart-lang/i18n/tree/main/pkgs/intl4x
issue_tracker: https://github.com/dart-lang/i18n/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aintl4x

platforms:
  web:
  android:
  ios:
  linux:
  macos:
  windows:

topics:
  - i18n

environment:
  sdk: ^3.12.0

dependencies:
  collection: ^1.19.1
  icu4x:
    git:
      url: https://github.com/unicode-org/icu4x
      path: ffi/dart
  meta: ^1.18.3
  timezone: ^0.11.0

dev_dependencies:
  args: ^2.7.0
  dart_flutter_team_lints: ^3.5.2
  dart_style: ^3.1.9
  test: ^1.31.1
